### ISSUE TITLE
Inbound and outbound action in win_firewall module.

### ISSUE THREAD

**Issue by sakar97** [ansible-collections/community.windows#133]
##### SUMMARY

Currently, the win_firewall module does not manage inbound and outbound action, whether allow inbound rules or block them and similar for outbound actions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_firewall
##### ADDITIONAL INFORMATION

```yaml
- name: Enable firewall for Domain, Public and Private profiles and block outbound actions
  community.windows.win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
    inbound: allow
    outbound: block
  tags: enable_firewall
```
