### ISSUE TITLE
Add win_iis_webhandler 

### ISSUE THREAD

**Issue by davetapley** [ansible-collections/community.windows#145]
##### SUMMARY

The `iis` modules are missing any way to manage handlers in IIS.

It looks like @arestarh had a PR ready to go to support this:
https://github.com/ansible/ansible/pull/45998

But it was rejected because:
> After some discussion at the Windows Working Group module review, we're a little nervous to take on more IIS modules into the core distribution right now, especially given the state of the other IIS modules we already have. This would be a good candidate for the new collections feature that's coming in Ansible 2.8, which would allow these modules to be hosted on galaxy.ansible.com and easily installed/upated by users on their Ansible controller.

https://github.com/ansible/ansible/pull/45998#issuecomment-459949742

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community.windows.win_iis_webhandler`

##### ADDITIONAL INFORMATION

```yaml
- name: Create http handler to process php files
  win_iis_webhandler:
    name: php-fastcgi
    script_processor: C:\ProgramData\php\php-cgi.exe
    modules: FastCgiModule
    path: '*.php'
    verb: '*'
    state: present
- name: Adds a handler named "testHandler" to the Default Web Site
  win_iis_webhandler:
    name: testHandler
    modules: IsapiModule
    path: '*.test'
    verb: 'GET,POST'
    site_name: Default Web Site
    state: present
```

⬆️ copied from: https://github.com/arestarh/ansible/blob/65c3857cfa8794240c529b54297e338c5dc6a376/lib/ansible/modules/windows/win_iis_webhandler.py#L123-L141

**Comment by davetapley** [comment]
It appears there might be a workaround for this using  [`ansible.windows.win_dsc`](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html).
The last [example](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html#examples) shows how [`dsccommunity/xWebAdministration `](https://github.com/dsccommunity/xWebAdministration) can be used:
```
- name: Create IIS Website with Binding and Authentication options
  ansible.windows.win_dsc:
    resource_name: xWebsite
...
````

And `xWebAdministration` appears to support [`webapplicationhandler`](https://github.com/dsccommunity/xWebAdministration#webapplicationhandler), which might be what we need.
