### ISSUE TITLE
 Regression: win_psrepository can't register repo.  It needs to support PowershellGet 1.0 once more

### ISSUE THREAD

**Issue by kinwolfqc** [ansible-collections/community.windows#160]
##### SUMMARY
We update our ansible install lately and are facing a problem that was working fine before

On a new windows 2016 server, only powershellget 1.0 is installed.  To be able to update PSGET on our new server, we need to register our internal repository and then we can install the latest powershellGet module.  But  win_psrepository refuses to register the internal repo, because it requires powershellget v1.6 (you do not need 1.6 to register a repo, that requirement should not be there)

So, the proverbial egg and chicken case, but the module really need to support v 1.0 since it's the default version on windows 2016 and windows 10.  

The requirement seems to have been included in this commit https://github.com/ansible-collections/community.windows/commit/4b4f98cd078f53104ff9bf53a677051f5a08a278 but not sure why by simply looking at the code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 win_psrepository

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/home/sma084pe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2016

##### STEPS TO REPRODUCE

```yaml
- name: Inscription du Repo nuGet&PowershellGet  
  community.windows.win_psrepository: 
    installation_policy:  trusted
    name: DepotPGet  
    source: "https://{{ depotPGet }}/nuget/PSGEt"
    state: present

```

##### EXPECTED RESULTS

The erpo is registered in windows

##### ACTUAL RESULTS

```paste below
fatal: [stnoy090.intro.techno.local]: FAILED! => {
    "changed": false,
    "msg": "PowerShellGet version 1.6.0+ is required."
}
```

**Comment by briantist** [comment]
The reason is that it's difficult to support the (now ancient) version 1.0 that comes out of the box with Windows; it doesn't even support modern TLS versions and will fail on most https repositories nowadays as a result.

If you look at the commit you linked, in `plugins/modules/win_psrepository.py` starting on Line 46, you can see that 1.6.0 was always the minimum supported version; it happened not to be enforced but that only led to issues of the code working partially or failing for unclear reasons in more and more cases as time goes on.

You can however, use [`win_psmodule`](https://docs.ansible.com/ansible/latest/collections/community/windows/win_psmodule_module.html) to install those required modules. Take a look at the Notes. Even though it has the same requirements, it has some checks to allow it to install those required modules when needed:
> On PowerShell 5.x required modules and a package provider will be updated under the first run of the win_psmodule module.

In my own setup I use it to install the required modules, something like this:
```yaml
- name: "Setup PackageManagement Module"
  community.windows.win_psmodule:
    name: PackageManagement
    minimum_version: 1.4.4.0

- name: "Setup PowerShellGet Module"
  community.windows.win_psmodule:
    name: PowerShellGet
    minimum_version: 2.2.5
```
