### ISSUE TITLE
Improve error handling when installing invalid packages via win_scoop

### ISSUE THREAD

**Issue by jwnmulder** [ansible-collections/community.windows#162]
##### SUMMARY

When installing invalid packages using win_scoop, the task does not fail.

To reproduce
```yaml
tasks:
    - name: Install scoop packages
      community.windows.win_scoop:
          name: invalidpackagename
          state: present
```

In addition, it seems that stdout is only present when running ansible in verbode mode '-vv'

When running without '-vv'
```json
{
   "changed":True,
   "rc":0,
   "failed":False,
   "failed_when_result":True
}
```

With '-vv'
```json
{
   "changed":True,
   "rc":0,
   "stdout":"Couldn't find manifest for 'invalidpackagename'.\n",
   "stdout_lines":[
      "Couldn't find manifest for 'invalidpackagename'."
   ],
   "failed":False,
   "failed_when_result":True
}
```

This means that error handling based on stdout content is not possible as ansible is not always executed in verbose mode

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_scoop

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
