### ISSUE TITLE
PropertyNotFound error when creating an attribute on an element

### ISSUE THREAD

**Issue by bpar476** [ansible-collections/community.windows#166]
##### SUMMARY

When using `win_xml` to add an attribute to an existing element, a `PropertyNotFound` error is raised.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_xml

##### ANSIBLE VERSION

```paste below
"2.10.3"
```

##### CONFIGURATION

Output was empty
```paste below
```

##### OS / ENVIRONMENT

Windows on Amazon EC2: Windows_Server-2019-English-Full-ContainersLatest-2020.07.15

##### STEPS TO REPRODUCE

```yaml
- name: Add proxy settings to server.xml
   community.windows.win_xml:
     path: "{{ app_version_folder }}\\conf\\server.xml"
     xpath: "//Server/Service/Connector"
     type: attribute
     fragment: "{{ item.value  }}"
     attribute: "{{ item.attribute }}"
   when: proxy_app_via_https_lb
   loop:
     - {attribute: 'proxyName', value: "{{ application_base_name }}"}
     - {attribute: 'proxyPort', value: "443"}
     - {attribute: 'scheme', value: "https"}
```

XML being parsed:
```
.
.
.
<Server shutdown="SHUTDOWN" port="8007">
  <Listener SSLEngine="on" className="org.apache.catalina.core.AprLifecycleListener"/>
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
  <Service name="Catalina">
    <Connector port="8085" redirectPort="8443" URIEncoding="UTF-8" useBodyEncodingForURI="true" maxHttpHeaderSize="8192" enableLookups="false" acceptCount="100" disableUploadTimeout="true" connectionTimeout="20000" minSpareThreads="25" maxThreads="150" protocol="HTTP/1.1">
      <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol"/>
    </Connector>
.
.
.
```

##### EXPECTED RESULTS

The `proxyName`, `proxyPort`, and `scheme` attributes should be inserted into the `Connector` element

##### ACTUAL RESULTS

The task fails and the following output occurs:

```paste below
<XX.XXX.XX.XXX> WINRM RESULT '<Response code 1, out "{"exception":"The pr", err "#< CLIXML\r\n<Objs Ver">'
<XX.XXX.XX.XXX> WINRM CLOSE SHELL: 855E2489-8F38-4501-81CC-D154ABAC1532
The full traceback is:
The property 'scheme' cannot be found on this object. Verify that the property exists.
At line:230 char:21
+                 if ($node.$attribute -ne $fragment) {
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 230
failed: [XX.XXX.XX.XXX] (item={'attribute': 'scheme', 'value': 'https'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "attribute": "scheme",
        "value": "https"
    },
    "msg": "Unhandled exception while executing module: The property 'scheme' cannot be found on this object. Verify that the property exists."
}
```
