### ISSUE TITLE
win_format: Unable to create filesystem on a drive with no letter assigned

### ISSUE THREAD

**Issue by senilio** [ansible-collections/community.windows#178]
##### SUMMARY

When attempting to create a filesystem on a drive that does not have a letter assigned, the module throws an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_format

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /home/x/x/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/x/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/x/x/ansible.cfg) = 25
DEFAULT_GATHERING(/home/x/x/ansible.cfg) = smart
HOST_KEY_CHECKING(/home/x/x/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target OS is Windows 2016 DC edition

##### STEPS TO REPRODUCE

Add 2 drives to a windows box. Assign a drive letter only to the first one. Try to create a filesystem on both.

```yaml
---
- hosts: all
  gather_facts: False
  connection: local
  vars:
    disk_init_windows:
      - label: Data
        disk_number: 1
        drive_letter: D
      - label: Log
        disk_number: 2
  tasks:
 
    - name: Get disk facts
      community.windows.win_disk_facts:

    - name: Initialize disk
      community.windows.win_initialize_disk:
        disk_number: "{{ item.disk_number }}"
        online: yes
        style: GPT
      loop: "{{ disk_init_windows }}"

    - name: Partition disk and assign letter
      community.windows.win_partition:
        disk_number: "{{ item.disk_number }}"
        drive_letter: "{{ item.drive_letter | default(omit) }}"
        partition_size: -1
        partition_number: 2
        read_only: no
        state: present
      loop: "{{ disk_init_windows }}"

    - name: Renew disk facts after partitioning
      community.windows.win_disk_facts:

    - name: Format disk
      community.windows.win_format:
        full: no
        path: "\\\\?\\Volume{{ ansible_disks[item.disk_number].partitions[-1].guid }}\\"
        force: no
        file_system: ntfs
        new_label: "{{ item.label }}"
        allocation_unit_size: 65536
      loop: "{{ disk_init_windows }}"
```

##### EXPECTED RESULTS

I expect a filesystem to be created on both drives, regardless if a drive letter is assigned or now.

##### ACTUAL RESULTS

When attempting to format the drive that does not have a letter assigned, the module throws an error.

```paste below
Using module file /home/x/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_format.ps1
Pipelining is enabled.
PSRP: EXEC (via pipeline wrapper)
The full traceback is:
The variable '$pristine' cannot be retrieved because it has not been set.
At line:185 char:9
+     if ($pristine) {
+         ~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (pristine:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : VariableIsUndefined

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 185
failed: [win2016] (item={'label': 'Log', 'disk_number': 2}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "disk_number": 2,
        "label": "Log"
    },
    "msg": "Unhandled exception while executing module: The variable '$pristine' cannot be retrieved because it has not been set."
}
```

When enabling force format by setting `force: yes`, both filesystem are successfully created. But this means that consequent runs will reformat the drives.
