### ISSUE TITLE
win_domain_user - ability to clear an attribute

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#18]
_From @thylocene on Feb 26, 2020 03:31_

##### SUMMARY

The win_domain_user module currently has no way to clear an attribute e.g. city, PostalCode, etc.

The module throws an error if an empty string is used for an attribute:

e.g.
Microsoft.ActiveDirectory.Management.ADInvalidOperationException: replace ---> System.ServiceModel.FaultException: Bad AttributeTypeAndValue or Change found inside the request.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_domain_user

##### ADDITIONAL INFORMATION

```yaml

---
  - name: Map the answers from the servicenow request to the AD attributes
    win_domain_user:
      name: "fredb"
      street: ""
      city: ""
      postal_code: ""
    register: user_created

```

_Copied from original issue: ansible/ansible#67764_
