### ISSUE TITLE
win_scheduled_task module is missing Windows 10 compatibility level

### ISSUE THREAD

**Issue by RRohi** [ansible-collections/community.windows#182]
##### SUMMARY

Compatibility parameter of win_scheduled_task module is missing Windows 10 option.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module: win_scheduled_task
Parameter: compatibility
##### ADDITIONAL INFORMATION

**win_scheduled_task** module has **compatibility** parameter that has its options maxed at Windows Vista/2008 at the moment.
Quote from the module docs: "2 means the task is compatible with Task Scheduler 2.0."

Although I would like to see a Windows 10 option, I guess it would be nice to add 7/2008 R2 option as well?

```yaml
# Lets say Windows 10 Compatibility level gets an ID of 4
- name: Scheduled Task with Windows 10 Compatibility level.
  community.windows.win_scheduled_task:
    name: 'Scheduled Task Example'
  compatibility: 4
```
