### ISSUE TITLE
win_rds_rap

### ISSUE THREAD

**Issue by Outek** [ansible-collections/community.windows#184]
##### SUMMARY
Somewhere in the creation of a RD Gateway-managed local computer groups is a bug.
The specified group existing on the Gatewayserver, but the Playbook fails with:
```yaml
fatal: [servername.domain.com]: FAILED! => {"changed": false, "msg": "COLL_LOCAL is not a valid gateway managed computer group"}
``` 

If i configure the rap manually, everthing is working fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Creation of Remote Desktop Gatewayserver Resource autorization policies.

##### ANSIBLE VERSION
```paste below
ansible 2.9.14
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
Windows Server 2019 1809

##### STEPS TO REPRODUCE
```yaml
- name: RDS RAP
  win_rds_rap:
    name: "RDG_RAP_COLL_LOCAL"
    allowed_ports: 3389
    description: "This is a Test"
    computer_group_type: rdg_group
    computer_group: "COLL_LOCAL"
    user_groups:
      - "group1@domain.com"
      - "group2@domain.com"
      - "group2@domain.com"
    state: enabled
```

On the Gatewayserver
```powershell
PS C:\Windows\system32> Test-Path -LiteralPath "RDS:\GatewayServer\GatewayManagedComputerGroups\COLL_LOCAL"
True
```

##### EXPECTED RESULTS
A RAP should be created with the Playbook
