### ISSUE TITLE
What about a Win_networks_facts ?

### ISSUE THREAD

**Issue by luclis** [ansible-collections/community.windows#200]
##### SUMMARY

Hi, I often use ansible facts in my playbook and now, I need to set interface name and IPAddress. It's just an little powershell command but I want to get the actual netadapter's name and/or id. 
Do you thinks it's a good idea to implement a win_networks_facts like your win_disks_facts ? 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_networks_facts
##### ADDITIONAL INFORMATION

IMHO, we could try to reproduce the ansible facts for Linux. Looking at [the documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html), I can found : 

```yaml
    "ansible_eth0": {
        "active": true,
        "device": "eth0",
        "ipv4": {
            "address": "REDACTED",
            "broadcast": "REDACTED",
            "netmask": "255.255.255.0",
            "network": "REDACTED"
        },
        "ipv6": [
            {
                "address": "REDACTED",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "REDACTED",
        "module": "xen_netfront",
        "mtu": 1500,
        "pciid": "vif-0",
        "promisc": false,
        "type": "ether"
    },
    "ansible_eth1": {
        "active": true,
        "device": "eth1",
        "ipv4": {
            "address": "REDACTED",
            "broadcast": "REDACTED",
            "netmask": "255.255.224.0",
            "network": "REDACTED"
        },
        "ipv6": [
            {
                "address": "REDACTED",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "REDACTED",
        "module": "xen_netfront",
        "mtu": 1500,
        "pciid": "vif-1",
        "promisc": false,
        "type": "ether"
    },
    "ansible_interfaces": [
        "lo",
        "eth1",
        "eth0"
    ],
```
