### ISSUE TITLE
Windows feature info module

### ISSUE THREAD

**Issue by gamethis** [ansible-collections/community.windows#208]
##### SUMMARY
Create a new module win_feature_info

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
```yaml
- name: get windows feature info
  community.windows.win_feature_info:
    name: RDS-Licensing
  register: feature_info

- name: get windows feature info for all features
  community.windows.win_feature_info:
  register: feature_info
```
##### ADDITIONAL INFORMATION
To provide information on the current state of a windows feature.
This is needed for queries about system state as well for making decisions about items like mounting the sxs folder so unavailable features can be added.

```yaml
- name: get windows feature info
  community.windows.win_feature_info:
    name: RDS-Licensing
  register: feature_info

- name: Install License Role
  ansible.windows.win_feature:
    name: RDS-Licensing
    state: present
  register: licensing_install
  when: feature_info.features[0].install_state == "Available"

- name: Install License Role
  ansible.windows.win_feature:
    name: RDS-Licensing
    state: present
    source: C:\temp\sxs\
  register: licensing_install
  when: feature_info.features[0].install_state == "Removed"
```
