### ISSUE TITLE
Unable to disable Windows Scheduled Task

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#22]
_From @Gianlu on Aug 02, 2018 16:53_

##### SUMMARY
Trying to disable a Windows Scheduled task throws an exception. The sintax to disable a task is described in documentation.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

win_scheduled_task
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = False
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/adminsalvo/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/modules']

##### OS / ENVIRONMENT

Ansible is running on Debian 9.5.
Target host is Windows 2012 R2
##### STEPS TO REPRODUCE

```yaml
   - name: read Scheduled tasks
     win_scheduled_task_stat:
     register: sched_tasks

   - name: stop it all
     win_scheduled_task:
       name: "{ item }}"
       enabled: no
       path: \
     when: item | lower is search("myprefix")
     with_items:
       - "{{ sched_tasks.folder_task_names }}"

```

##### EXPECTED RESULTS

changed: [myserver] => (item=myprefix_task01)
##### ACTUAL RESULTS

```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_scheduled_task.ps1
<myserver> ESTABLISH WINRM CONNECTION FOR USER: None on PORT 5985 TO drwebin01
checking if winrm_host myserver is an IPv6 address
EXEC (via pipeline wrapper)
failed: [myserver] (item=myprefix_task01) => {
    "changed": false,
    "item": "myprefix_task01",
    "msg": "failed to modify scheduled task: Exception calling \"RegisterTaskDefinition\" with \"6\" argument(s): \"The user name or password is incorrect. (Exception from HRESULT: 0x8007052E)\""
}

```
The password is correct because when i run 
```powershell
Get-ScheduledTask -TaskName myprefix_task01 | Enable-ScheduledTask
```
The task is enabled (or disabled). Also the command
```powershell
Get-ScheduledTask -TaskName myprefix_task01 | Start-ScheduledTask
```
is successfull.

Thank you.

_Copied from original issue: ansible/ansible#43612_
