### ISSUE TITLE
New Module win_ini_file

### ISSUE THREAD

**Issue by gamethis** [ansible-collections/community.windows#222]
##### SUMMARY

create windows equivalent of https://docs.ansible.com/ansible/2.5/modules/ini_file_module.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Windows Operating systems have loads of INI files.
It would be nice to have the same features as linux systems.
this is also helpful when defining MS SQL servers and other apps on windows.

##### ADDITIONAL INFORMATION

```yaml
- name: Ensure "fav=lemonade is in section "[drinks]" in specified file
  community.windows.win_ini_file:
    path: c:\path\to\file.ini
    section: drinks
    option: fav
    value: lemonade
    backup: yes
```
