### ISSUE TITLE
win_dns_record: Add multiple SRV records with same name

### ISSUE THREAD

**Issue by snakeego** [ansible-collections/community.windows#225]
##### SUMMARY
Need create multiple SRV records for one DNS name, Now records are overriding.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION
I have two solution ideas:

1. Add SRV records as multiple A, but use dict instead str
```yaml
community.windows.win_dns_record:
  zone: "example.com"
  type: SRV
  name: "_smtp._tcp"
  values: 
    - value: smtp001
      port: 25
      priority: 10
      weight: 1
    - value: smtp002
      port: 25
      priority: 10
      weight: 1
```
2. Add new state `append` for prevent deletion other records
```yaml
- community.windows.win_dns_record:
    zone: "example.com"
    type: SRV
    name: "_smtp._tcp"
    value: smtp001
    port: 25
    priority: 10
    weight: 1
- community.windows.win_dns_record:
    zone: "example.com"
    type: SRV
    value: smtp002
    port: 25
    priority: 10
    weight: 1
    state: append
```
