### ISSUE TITLE
How to set the user with win_nssm?

### ISSUE THREAD

**Issue by nre-ableton** [ansible-collections/community.windows#227]
##### SUMMARY

The documentation of the `win_nssm` module states that the `user` parameter is deprecated:

> DEPRECATED, will be removed in a major release after 2021-07-01, please use the ansible.windows.win_service module instead.

However, setting a user with a `win_nssm` service doesn't work. The task succeeds, but the service then fails to start. Why is the `user` parameter being deprecated anyway? Is there something wrong with the service created by `win_nssm` such that it can't be modified by `win_service`?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`win_nssm`

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/nre/<redacted>/ansible.cfg
  configured module search path = ['/home/nre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nre/<redacted>/lib/python3.8/site-packages/ansible
  executable location = /home/nre/<redacted>/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/nre/<redacted>/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/nre/<redacted>/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/nre/<redacted>/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/nre/<redacted>/ansible.cfg) = ['/home/nre/<redacted>/ansible/playbooks/inventory']
DEFAULT_ROLES_PATH(/home/nre/<redacted>/ansible.cfg) = ['/home/nre/<redacted>/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/nre/<redacted>/ansible.cfg) = /home/nre/<redacted>/ansible/playbooks/vault/vault-password
HOST_KEY_CHECKING(/home/nre/<redacted>/ansible.cfg) = False
INVENTORY_ENABLED(/home/nre/<redacted>/ansible.cfg) = ['yaml']
RETRY_FILES_ENABLED(/home/nre/<redacted>/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

So I have the following tasks in one of my playbooks:

```yaml
- name: Create Windows service with NSSM
  win_nssm:
    name: "{{ jenkins_swarm_service_name }}"
    application: "{{ get_command_java.stdout | trim }}"
    arguments: "{{ jenkins_swarm_full_args }}"
    description: "Jenkins Swarm Client"
    working_directory: "{{ jenkins_swarm_home }}"
    state: stopped

- name: Set Jenkins Swarm Client to run as Jenkins user
  win_service:
    name: "{{ jenkins_swarm_service_name }}"
    username: "{{ jenkins_config_owner }}"
    password: "{{ jenkins_user_password }}"
    state: stopped
```

Both tasks succeed, but when I attempt to start the service later in the playbook, it fails with an error: "Service 'Jenkins Swarm Client (Jenkins Swarm Client)' cannot be started due to the following error: Cannot start service Jenkins Swarm Client on computer"

I am currently working around the error with this task:

```yaml
- name: Set Jenkins Swarm Client to run as Jenkins user
  win_shell: >
    nssm.exe set \
      '{{ jenkins_swarm_service_name }}' \
      ObjectName .\\{{ jenkins_config_owner }} {{ jenkins_user_password }}
```

##### EXPECTED RESULTS

The service starts without problems.

##### ACTUAL RESULTS

```paste below
TASK [ableton.jenkins_swarm_client : Start Windows service] ********************
Wednesday 14 April 2021  17:07:51 +0200 (0:00:00.034)       0:05:36.542 ******* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 1028
fatal: [generic-win-vs2019-sandbox]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Service 'Jenkins Swarm Client (Jenkins Swarm Client)' cannot be started due to the following error: Cannot start service Jenkins Swarm Client on computer '.'."}
```
