### ISSUE TITLE
Set userAccountControl value with win_domain_computer

### ISSUE THREAD

**Issue by NORRIM08** [ansible-collections/community.windows#232]
##### SUMMARY
win_domain_computer supports control of only a very limited quantity of fields, especially as compared to win_domain_user. In particular, I would like to see functionality to modify the value of attribute userAccountControl. More generally, it would be helpful if it allowed access to modifying attributes in general as win_domain_user does.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_domain_computer

##### ADDITIONAL INFORMATION
The feature would be used to create more useful, customizable computer objects. I believe it is necessary because currently only very basic, generic computers can be created that may not be suitable for most use-cases.

```yaml
  - name: create computer
    community.windows.win_domain_computer:
       name: "{{ machineName }}"
       state: present
       attributes:
          userAccountControl: "{{ someValue }}"
       sam_account_name: "{{ machineName|upper }}$"
       dns_hostname: "{{ machineName }}.{{ domainName }}"
       ou: ou=example, ou=example, dc=example, dc=example, dc=com
       description: "Computer object with customized userAccountControl value"
       domain_server: "{{ someServer }}"
       domain_username: "{{ someUsername }}"
       domain_password: "{{ somePassword }}"
```

**Comment by jborean93** [comment]
The `win_domain_computer` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.computer](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/computer_module.html#ansible-collections-microsoft-ad-computer-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-computer) for more info on how to change your code to use the newer module.

The `microsoft.ad.computer` module contains an `attributes` option which can be used to set any LDAP attributes on an object, including `userAccountControl`. It would look like:

```yaml
- microsoft.ad.computer:
    name: name
    state: present
    attributes:
      set:
        userAccountControl: '{{ some_value }}'
```
