### ISSUE TITLE
win_xml error "The property 'SchemaInfo' cannot be found on this object. Verify that the property exists." when in xml file had <!

### ISSUE THREAD

**Issue by snsiregar** [ansible-collections/community.windows#243]
##### SUMMARY

I try to automate adding service on tectia server using ansible, so what to do is editing tectia config server (tectia.xml).
so, first I try run playbook for simple.xml and no issue.
but when try to run for tectia.xml get error.
```
{
    "exception": "The property 'SchemaInfo' cannot be found on this object. Verify that the property exists.\r\nAt line:135 char:1\r\n+ $namespaceMgr.AddNamespace($xmlorig.$localname.SchemaInfo.Prefix, $na ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : PropertyNotFoundStrict\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 135\r\n",
    "_ansible_no_log": false,
    "msg": "Unhandled exception while executing module: The property 'SchemaInfo' cannot be found on this object. Verify that the property exists.",
    "changed": false
}
 ```

so, I compare simple.xml and tectia.xml
the different is on tectia.xml have
 ```
<!DOCTYPE secsh-server SYSTEM "C:\tectia\ssh-server-ng-config-1.dtd">
 ```
under xml version, but simple.xml doesnt.

and then I try remove that extra line on tectia.xml, then run again and success.
but tectia service cannot running without it.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
Ansible 2.9.1
```

##### OS / ENVIRONMENT

Windows Server 2019

##### STEPS TO REPRODUCE

```yaml
win_xml:
      path: C:\tectia\tectia.xml
      xpath: '/secsh-server/services/rule[@group="siregar"]/subsystem'
      fragment: '<attribute name="virtual-folder" value="folder=S:\siregar\" />'
```
