### ISSUE TITLE
win_domain_group_membership: Group members can't be set when state is pure

### ISSUE THREAD

**Issue by CathalMullan** [ansible-collections/community.windows#256]
##### SUMMARY
When setting the members of a group using `win_domain_group_membership`, they are added then removed within the same task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_group_membership

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.1]
  config file = /home/cathal/workspace/ansible/ansible.cfg
  configured module search path = ['/home/cathal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cathal/workspace/ansible/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cathal/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cathal/workspace/ansible/.venv/bin/ansible
  python version = 3.9.2 (default, Mar 24 2021, 13:57:04) [GCC 7.5.0]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION
```paste below
DEFAULT_FORKS(/home/cathal/workspace/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/home/cathal/workspace/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/cathal/workspace/ansible/ansible.cfg) = ['/home/cathal/workspace/ansible/vagrant.ini']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/cathal/workspace/ansible/ansible.cfg) = True
DEFAULT_POLL_INTERVAL(/home/cathal/workspace/ansible/ansible.cfg) = 3
DEFAULT_ROLES_PATH(/home/cathal/workspace/ansible/ansible.cfg) = ['/home/cathal/workspace/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/cathal/workspace/ansible/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/home/cathal/workspace/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/cathal/workspace/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/cathal/workspace/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/cathal/workspace/ansible/ansible.cfg) = ['ini', 'yaml']
```

##### OS / ENVIRONMENT
Target OS is Windows Server 2019.

##### STEPS TO REPRODUCE
1. Create a new domain group
2. Add a domain group member with state set to `pure`

```yaml
- name: Create database group
  community.windows.win_domain_group:
    name: database_group
    scope: global

- name: Set database group members
  community.windows.win_domain_group_membership:
    name: database_group
    state: pure
    members:
      - "DATABASE$"
```

##### EXPECTED RESULTS
The member is added to group.

##### ACTUAL RESULTS
The member is added and removed within the same task, resulting in the member not actually being added to the group.

```paste below
# v1.4.0
changed: [controller] => changed=true
  added:
  - DATABASE$
  members: []
  removed:
  - DATABASE$
```

This worked as expected on v1.3.0, the issue seems to have been introduced with v1.4.0.

```
# v1.3.0
changed: [controller] => changed=true
  added:
  - DATABASE$
  members:
  - DATABASE$
  removed: []
```
