### ISSUE TITLE
win_domain_user documentation is really confusing

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/community.windows#258]
##### SUMMARY

When adding a domain user with a name that is longer than 20 chars the module fails.
This is not very surprising since that is the max for the 'SAMAccountName'

Please update the docs so that people don't need to spend hours in figuring out why their name gets rejected all the time.
Mentioning that the upn can be longer would be a good one to. (also mention the max length of that one and if that is with or without the @DOMAIN)
The ad user/groups tool allows to set this and then simply trunks the samaccountname to the first 20 chars of the userprincipalname.

Also it is currently mentioned that the following are needed to specify the admin account to create the domain user.
- domain_username
- domain_password
These options are really confusing, yes you could need them in some cases but the description should mention those.

domain_password is required if domain_username is set, this should be in the description.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

win_domain_user
##### ANSIBLE VERSION

```paste below

```

**Comment by RobVerduijn** [comment]
Add a working example that shows the use of upn and samaccount and mentions the difference

working example
add multiple domain users and add them to their groups using the upn and truncking the upn to the max length of name (20 chars)
```
- name: add multiple domain users
  hosts: ad01.addomain.test
  gather_facts: false
  become: false
  remote_user: addomain_admin
  connection: winrm
  collections:
     - community.windows
  vars:
    ad_domain: addomain.test
    domain_users:
        - upn: longusernameover20chars
          password: secret
          groups:
             - Domain Users
        - upn: shortname
          password: secret
          groups:
             - Domain Users
             - Domain Admins
  
  tasks:
  - name: add domain users
    community.windows.win_domain_user:
      upn: "{{ item.upn }}@{{ ad_domain }}"
      name: "{{ item.upn[:20] }}"  # the max length of name is 20 chars (SAMAccountName)
      groups: "{{ item.groups }}"
      state: present
    loop: "{{ domain_users }}"
```
