### ISSUE TITLE
win_domain_user - mark password as no_log

### ISSUE THREAD

**Issue by t-readyroc** [ansible-collections/community.windows#262]
##### SUMMARY

Currently when using the win_domain_user module, the user details, including the password, are returned plaintext. If possible, would be great to have the password marked as a no_log attribute.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_domain_user

##### ADDITIONAL INFORMATION

```yaml
---

- hosts: all
  tasks:
    - name: Create the admin user
      community.windows.win_domain_user:
        name: "{{ item.name }}"
        firstname: "{{ item.firstname }}"
        surname: "{{ item.lastname }}"
        password: "{{ item.password }}"
        password_never_expires: yes
        user_cannot_change_password: yes
        state: present
        groups:
          - DnsAdmins
          - DHCP Administrators
      loop: "{{ admin_accts }}"
```

Currently results in:

```shell
TASK [Create the admin user] ******************************************************************************************************************************************************************************
changed: [host.example.org] => (item={'name': 'testuser', 'firstname': 'test', 'lastname': 'user', 'password': 'plaintextpassword'})
```

**Comment by jborean93** [comment]
This is because you are looping a list of dicts and the default action there is to print out the representation of the whole dictionary. Setting `no_log` for password in the module won't do anything to help you here and currently it's not an issue because the module doesn't output the module invocation args.

What you should be doing is either set `no_log: True` on the task itself or better yet define the [loop label](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#limiting-loop-output-with-label) like so

```yaml
- name: Create the admin user
  community.windows.win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.lastname }}"
    password: "{{ item.password }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    state: present
    groups:
      - DnsAdmins
      - DHCP Administrators
  loop: "{{ admin_accts }}"
  loop_control:
    label: '{{ item.name }}'
```

Although this may not work in higher verbosities if it shows the loop item in the registered module results. You should try both options to see how it goes. In any case this is a behaviour of the controller and not the module itself and there are workarounds in place so I'm closing this issue.
