### ISSUE TITLE
community.windows.win_domain_computer isn't working

### ISSUE THREAD

**Issue by XDavidT** [ansible-collections/community.windows#269]
##### SUMMARY
After read carefully all the documentation of this repo, I've got confused.
Seem that Ansible isn't connected directly to the Active directory and needs a bridge windows machine,
by that I put my PC name in 'delegate_to' to continue, but an error was showed up saying port 22 is closed.
So I was more confused, since Ansible isn't connected directly to AD and also needs a Windows machine, and still wants 22 port - ssh port.
To continue I add the OpenSSH server feature to Windows, and added my pc to the inventory file with user and password to help Ansible login automatically. 
After trace the logs, saw the service is trying to connect in UNIX style, but it is a windows machine, so now I'm really confused.

What is the "windows bridge" the documentation talks about? How do I need to provide it to Ansible ? 😖

##### ISSUE TYPE
- Bug Report
- Missing information

##### COMPONENT NAME
community.windows.win_domain_computer

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xdavidt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

##### COLLECTION VERSION
1.5.0

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost

  tasks:
  - name: Import secrets
    include_vars:
      file: secrets.yml
      name: secret
    
  - name: Debug secrets
    ansible.builtin.debug:
      msg: Username found - {{secret.username}}

  - name: Add new Obj to AD
    community.windows.win_domain_computer:
      domain_server: domainDC.domain.com
      domain_username: "{{secret.adusername}}"
      domain_password: "{{secret.password}}"
      name: Test-Server
      dns_hostname: Test-Server.domain.com
      ou: "OU=Desktops,OU=Home,OU=Int,DC=domain,DC=com"
      description: Example of Ansible test
      enabled: yes
      state: present
    delegate_to: PC-NAME
```

##### EXPECTED RESULTS
Find my new object 'Test-server' in the 'Home' ou in the AD.

##### ACTUAL RESULTS
```
TASK [Add new Obj to AD] **************************************************************************************************************************************************************************************************
task path: /home/xdavidt/Yamls/ad_add_obj.yml:14
<PC-NAME> ESTABLISH SSH CONNECTION FOR USER: myuser
<PC-NAME> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="myuser"' -o ConnectTimeout=10 -o ControlPath=/home/xdavidt/.ansible/cp/e1165a38df PC-NAME '/bin/sh -c '"'"'echo ~myuser && sleep 0'"'"''
<PC-NAME> (1, b'', b'The system cannot find the path specified.\r\n')
<PC-NAME> Failed to connect to the host via ssh: The system cannot find the path specified.
<PC-NAME> ESTABLISH SSH CONNECTION FOR USER: myuser
<PC-NAME> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="myuser"' -o ConnectTimeout=10 -o ControlPath=/home/xdavidt/.ansible/cp/e1165a38df PC-NAME '/bin/sh -c '"'"'echo "`pwd`" && sleep 0'"'"''
<PC-NAME> (1, b'', b'The system cannot find the path specified.\r\n')
<PC-NAME> Failed to connect to the host via ssh: The system cannot find the path specified.
<PC-NAME> ESTABLISH SSH CONNECTION FOR USER: myuser
<PC-NAME> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="myuser"' -o ConnectTimeout=10 -o ControlPath=/home/xdavidt/.ansible/cp/e1165a38df PC-NAME '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1625662559.8701348-238508631144874 `" && echo ansible-tmp-1625662559.8701348-238508631144874="` echo ~/.ansible/tmp/ansible-tmp-1625662559.8701348-238508631144874 `" ) && sleep 0'"'"''
<PC-NAME> (1, b'', b'The system cannot find the path specified.\r\n')
<PC-NAME> Failed to connect to the host via ssh: The system cannot find the path specified.
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1625662559.8701348-238508631144874 `\" && echo ansible-tmp-1625662559.8701348-238508631144874=\"` echo ~/.ansible/tmp/ansible-tmp-1625662559.8701348-238508631144874 `\" ), exited with result 1",
    "unreachable": true
}
```
