### ISSUE TITLE
Add lmhostlookup configuration to win_netbios

### ISSUE THREAD

**Issue by agowa338** [ansible-collections/community.windows#271]
##### SUMMARY
Please add an option to toggle lmhostlookup within win_netbios. This option is also within the wins section of the adapter configuration.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_netbios

##### ADDITIONAL INFORMATION

```yaml
- name: Disable NetBIOS system wide
  community.windows.win_netbios:
    state: disabled
    lmhostlookup: disabled
```
