### ISSUE TITLE
Specifing a remote DNS server with computer_name doesn't work anymore since v1.6.0

### ISSUE THREAD

**Issue by ntimo** [ansible-collections/community.windows#276]
##### SUMMARY
Specifying a remote computer_name in the `win_dns_record` module doesn't work anymore.

This is likely due the change in https://github.com/ansible-collections/community.windows/commit/f677f94d4126fa17ccab96a2dd50ed9cfbdbaa31#diff-795bc7066e5c113a02653007e502feb512eb54d1089b4dc95f73a316e70eda79R34 which changed the "module.Params.computer_name" to "module.Params.server" 

When you try to specify the module param server the role breaks. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_dns_record

##### ANSIBLE VERSION
2.10.9

##### COLLECTION VERSION
1.6.0

##### OS / ENVIRONMENT
Windows Server 2016

##### STEPS TO REPRODUCE
Create the following step to create DNS entries on a remote host using a jump windows host.
```yml
- name: Create Server DNS entries
  become: yes
  win_dns_record:
    computer_name: "{{ dns_server }}"
    name: "test-record"
    type: "A"
    value: "{{ host_ip }}"
    state: present
    zone: "example.com"
  delegate_to: ansible02.example.com
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    ansible_user:
    ansible_password:
    ansible_become_method: runas
    ansible_become_user:
    ansible_become_pass:
```

##### EXPECTED RESULTS
The DNS entry is not created and the module fails with an error.

##### ACTUAL RESULTS
The DNS record is not created.
