### ISSUE TITLE
win_iis_website parameters logfile.customFields

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#28]
_From @Roxyrob on Dec 30, 2018 18:20_

##### SUMMARY

Cannot configure logfile.customFields

##### ISSUE TYPE
- Bug Report

Cannot configure logfile.customFields
using different syntax like:
logfile.customFields:{logFieldName:X-Forwarded-For,sourceName:X_FORWARDED_FOR,sourceType:RequestHeader}

also using different format without dictionary delimiter "{}", using "=" instead of ":" enclosing in "" or ''.
Someone knows if this is a bug/limitation ? It is possible to set this logfile.customFields using win_iis_website module or it is necessary to use win_commando/win_shell  modules ?

##### COMPONENT NAME

win_iis_website

##### ANSIBLE VERSION

```
ansible 2.7.1
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

_Copied from original issue: ansible/ansible#50407_

**Comment by jborean93** [comment]
_From @ShachafGoldstein on May 17, 2019 10:29_

Mind adding an example playbook to check with?

**Comment by jborean93** [comment]
_From @Rukas on Dec 18, 2019 13:45_

@Roxyrob I haven't had any luck using the `win_iis_website` module but we currently use `win_dsc` with the `XIisLogging` resource from the `xWebAdministration` PowerShell DSC module.  Here's an example of how we do it:

``` YAML
---
- hosts: all
  tasks:
    - name: Install xWebAdministration PowerShell Module
      win_psmodule:
        name: 'xWebAdministration'
        state: present
    - name: Configure IIS logging
      win_dsc:
        resource_name: xIisLogging
        LogPath: "%SystemDrive%\\inetpub\\logs\\LogFiles"
        LogFlags:
          - 'Date'
          - 'Time'
          - 'ClientIP'
          - 'ServerPort'
          - 'Method'
          - 'UriStem'
          - 'UriQuery'
          - 'HttpStatus'
          - 'BytesSent'
          - 'BytesRecv'
          - 'TimeTaken'
          - 'ProtocolVersion'
          - 'Host'
          - 'UserAgent'
          - 'Referer'
        LogPeriod: Daily
        LogFormat: W3C
        LoglocalTimeRollover: true
        LogCustomFields:
          - LogFieldName: x-forwarded-for
            SourceName: X-Forwarded-For
            SourceType: RequestHeader
```
