### ISSUE TITLE
win_domain_user: Unable to create a user with a name longer than 20 characters.

### ISSUE THREAD

**Issue by kurokobo** [ansible-collections/community.windows#281]
##### SUMMARY

Unable to create a user with a name longer than 20 characters using `win_domain_user`.

The maximum length of `sAMAccountName` is 20 characters due to pre-Windows 2000 restrictions, so if the account to be created has a long UPN or name, we will need to provide an alternative shorter name for `sAMAccountName`. Example:

- Name: `over20charactersaccount`
- UPN: `over20charactersaccount@ansible.local`
- SAM Account Name: `o20c` 👈 **This have to be shorter than 20 chars**

However, [in the current implementation](https://github.com/ansible-collections/community.windows/blob/693c9cfb35ad89406c171a7cfcaa4741f796fd3f/plugins/modules/win_domain_user.ps1#L164), `sAMAccountName` will be configured as same as `<username>` in `upn` if specified, or as `name` as default behavior of `New-ADUser` if not specified. Although we can change the `sAMAccountName` of an already **existing user** using `attributes` parameter, there is no way to set an arbitrary `sAMAccountName` when **creating a new one** using `win_domain_user`.

So if we try to create an account with a slightly longer name, the `sAMAccountName` will be longer than 20 characters and the task will fail.

There was already a #258, but that was about documentation instead of implementation, so I made this new issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`win_domain_user`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/demo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/demo/.venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/demo/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/demo/.venv/bin/ansible
  python version = 3.9.2 (default, Mar 10 2021, 17:29:56) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.windows

# /home/demo/.venv/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.6.0  

# /home/demo/.venv/lib64/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.6.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$ 
```

##### OS / ENVIRONMENT

- Controller
  - CentOS Linux release 8.2.2004
- Target
  - Windows Server 2019 Standard

##### STEPS TO REPRODUCE

1. Deploy Windows Server 2019 and set Active Directory Domain Service up.
2. Configure WinRM for Ansible
3. Run Playbook

```yaml
---
- hosts: addc
  gather_facts: false

  tasks:
    # Will be completed as Changed
    - name: Ensure user bob is present
      community.windows.win_domain_user:
        name: bob
        password: B0bP4ssw0rd
        update_password: on_create
        state: present

    # Failed
    - name: Ensure user over20charactersaccount is present
      community.windows.win_domain_user:
        name: over20charactersaccount
        password: B0bP4ssw0rd
        update_password: on_create
        state: present
```

##### EXPECTED RESULTS

The `sAMAccountName` can be specified when creating a new user, and an user with more than 20 characters can be created.

##### ACTUAL RESULTS

Playbook failed with error `The name provided is not a properly formed account name`.

```paste below
$ ansible-playbook -i inventory site.yml 

PLAY [addc] ****************************************************************************************************

TASK [Ensure user bob is present] ******************************************************************************
ok: [192.168.0.218]

TASK [Ensure user over20charactersaccount is present] **********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()
fatal: [192.168.0.218]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: The name provided is not a properly formed account name"}

PLAY RECAP *****************************************************************************************************
192.168.0.218              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

##### WORKAROUND
The current workaround is to create a user with a short UPN (which will be used as `sAMAccountName`) first, and then modify the UPN by `attributes` parameter instead of `upn` in the next task.

```yaml
    - name: Ensure user over20charactersaccount with short upn is present
      community.windows.win_domain_user:
        identity: CN=over20charactersaccount,CN=Users,DC=ansible,DC=local
        name: over20charactersaccount
        upn: o20c@ansible.local
        password: B0bP4ssw0rd
        update_password: on_create
        state: present

    - name: Ensure upn for over20charactersaccount is updated
      community.windows.win_domain_user:
        identity: CN=over20charactersaccount,CN=Users,DC=ansible,DC=local
        name: over20charactersaccount
        attributes:
          userPrincipalName: over20charactersaccount@ansible.local
        state: present
```
