### ISSUE TITLE
win_psmodules taking unreasonable long time to execute with modules already installed

### ISSUE THREAD

**Issue by tonyhogsten** [ansible-collections/community.windows#286]
##### SUMMARY
Running win_psmodules to install 5 modules (that are already installed) in a with_items loop, taking 3 minutes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_psmodules

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4]
  config file = /var/lib/awx/projects/***-ansible-workflows/ansible.cfg
  configured module search path = ['/var/lib/awx/projects/***-ansible-workflows/__library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /var/lib/awx/projects/***-ansible-workflows/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version

community.windows 1.6.0
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = False
CALLBACKS_ENABLED(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = ['profile_tasks']
COLLECTIONS_PATHS(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = ['/var/lib/awx/projects/***-ansible-workflows/collections']
DEFAULT_LOOKUP_PLUGIN_PATH(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = ['/var/lib/awx/projects/***-ansible-workflows/__lookup_plugins']
DEFAULT_MODULE_PATH(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = ['/var/lib/awx/projects/***-ansible-workflows/__library']
DEFAULT_MODULE_UTILS_PATH(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = ['/var/lib/awx/projects/***-ansible-workflows/__/module_utils']
DEFAULT_POLL_INTERVAL(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = 5
DISPLAY_SKIPPED_HOSTS(/var/lib/awx/projects/***-ansible-workflows/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Template running from AWX against a server running windows server 2016 on vmware. 

##### STEPS TO REPRODUCE

```yaml
### Tasks from role
- name: Set fact of required dscmodules
  set_fact:
    dsc_modules:
      - name: xPendingReboot
        version: 0.3.0.0
      - name: xDSCDiagnostics
        version: 2.6.0.0
      - name: xPSDesiredStateConfiguration
        version: 6.4.0.0
      - name: ComputerManagementDsc
        version: 8.4.0

- name: Ensure dsc modules are installed  
  win_psmodule:
    name: "{{ item.name }}"
    required_version: "{{ item.version }}"
    state: present
  with_items: "{{ dsc_modules }}"
```

##### EXPECTED RESULTS
Taking a lot less time determining that the modules are already present

##### ACTUAL RESULTS
It's taking a total of 200 seconds. 

```paste below
***_ansible.dsc_os.dsc_os_windows : Ensure dsc modules are installed - 200.87s
4407
/tmp/awx_8132_6lst7mj7/project/collections/ansible_collections/***_ansible/dsc_os/roles/dsc_os_windows/tasks/windows_server_base.yml:63 
```
