### ISSUE TITLE
win_dns_record - allow for creation of apex record

### ISSUE THREAD

**Issue by gitet** [ansible-collections/community.windows#306]
##### SUMMARY

I have an existing zone "foo.example.com". 
I want to create an apex record for "foo.example.com".

There does not seem to be a way to do this using the `win_dns_record` module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`win_dns_record`

##### ADDITIONAL INFORMATION

Could not find any hints in the docs about how to do this.
Tried the following:

```yaml
- name: create apex record 
  community.windows.win_dns_record:
    name: ""
    type: "A"
    value: "10.1.1.1"
    zone: "foo.example.com"
```
...but this results in an error.

**Comment by gitet** [comment]
Ah! Using "@" did the trick:

```
- name: create apex record 
  community.windows.win_dns_record:
    name: "@"
    type: "A"
    value: "10.1.1.1"
    zone: "foo.example.com"
```
Maybe you could consider the above example as something that could be added to the docs?
