### ISSUE TITLE
win_iis_webbindig cannot update ssl cert on default binding

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#31]
_From @pawellrus on Feb 08, 2019 15:51_

##### SUMMARY
win_iis_webbindig cannot update ssl cert on default binding
Catch-all binding becomes corrupted with SNI Flag enabled. IIS Binding console failed to open after execution. So I can roll it back only via IIS config file. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_iis_webbinding

##### ANSIBLE VERSION
```
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### OS / ENVIRONMENT
```
Ansible: Centos 7
Control: Windows Server 2016
```

##### STEPS TO REPRODUCE
```
- name: Configure binding without SNI
      win_iis_webbinding:
        name: Service
        protocol: https
        state: present
        port: 443
        certificate_hash: '**hash**'
```

##### EXPECTED RESULTS

Certificate on catch-all binding changed

##### ACTUAL RESULTS
```
failed: [server] (item={u'header': u'', u'hash': u'**hash**'}) => {
    "changed": true,
    "item": {
        "hash": "**hash**",
        "header": ""
    },
    "msg": "Failed to set new SSL certificate - Value does not fall within the expected range."
}
```

_Copied from original issue: ansible/ansible#51967_
