### ISSUE TITLE
win_power_plan: change power plan by alias or GUID (to make it work on non-english systems)

### ISSUE THREAD

**Issue by jrjsmrtn** [ansible-collections/community.windows#310]
##### SUMMARY

Allow the `win_power_plan` to be changed by `alias` or `guid`  instead of `name` to make it work on english and non-english systems. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_power_plan

##### ADDITIONAL INFORMATION

- Allow the `win_power_plan` to be changed by `alias` or `guid`  instead of `name`:

  ```yaml
  - name: Change power plan to high performance
    community.windows.win_power_plan:
      alias: SCHEME_MAX
  ```
  ```yaml
  - name: Change power plan to high performance
    community.windows.win_power_plan:
      guid: a1841308-3541-4fab-bc81-f71556f20b4a
  ```

  The power schemes properties on a french system are:
  ```
  Name                 Alias           Guid
  ----                 -----           ----
  Utilisation normale  SCHEME_BALANCED 381b4222-f694-41f0-9685-ff5bb260df2e
  Performances élevées SCHEME_MIN      8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
  Économie d'énergie   SCHEME_MAX      a1841308-3541-4fab-bc81-f71556f20b4a
  ```

- Changing `win_power_plan` by (english) name:
  ```yaml
  - name: Change power plan to high performance
    community.windows.win_power_plan:
      name: high performance
  ```

  fails on non-english systems:
  ```
  fatal: [a-random-pc]: FAILED! => changed=false
    all_available_plans:
      Performances élevées: false
      Utilisation normale: true
      Économie d'énergie: false
    msg: 'Defined power_plan: (high performance) is not available'
    power_plan_enabled: null
    power_plan_name: high performance
  ```
