### ISSUE TITLE
win_dns_record not getting credentials properly

### ISSUE THREAD

**Issue by ElioLopez** [ansible-collections/community.windows#315]
##### SUMMARY
I'm using the win_dns_record module in tower 3.8.3 in openshift, but it doesn't have an option to put the credentials to be used, or at least not in the documentation.
The only way to fill in the required "ansible_user" and "ansible_password" credentials is explicitly in the "extra variables" section, with its no convenient against security concerns.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_dns_record

##### ANSIBLE VERSION
```
sh-4.2$ ansible --version
#ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
sh-4.2$
```
##### OS / ENVIRONMENT
openshift 4.8.10

##### STEPS TO REPRODUCE

even when setting the variables explicitly within the playbook as fact (user and password are variables stored encrypted in a vault) , they are not taking in account in the module:

```yaml
- set_fact:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"

- debug:
    msg: "Ansible user set by fact is {{ ansible_user }}"

- name: Create A record
  community.windows.win_dns_record:
    name: "{{ vm_name|upper }}"
    type: "A"
    value: "{{ vm_ip }}"
    zone: "{{ selected_zone }}"
```

##### EXPECTED RESULTS
that the ansible_user and ansible_password are considered

##### ACTUAL RESULTS
as you can see below, the user is actually "root" which is incorrect:
```
TASK [Gathering Facts] *********************************************************
task path: /tmp/bwrap_1535_6eo1vcx_/awx_1535_5bwcwf0t/project/windows_management_playbooks/automate.yaml:1
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<dc.masked.com> ESTABLISH WINRM CONNECTION FOR USER: root on PORT 5985 TO dc.masked.com
fatal: [dc.masked.com]: UNREACHABLE! => {
    "changed": false, 
    "msg": "plaintext: auth method plaintext requires a password", 
    "unreachable": true
}
```
if I set ansible_user and ansible_password explicitly in the extra vars section ist works properly.
maybe the username and password variables should be added to the module itself.
Regards,
