### ISSUE TITLE
Extract only subfolder with win_unzip

### ISSUE THREAD

**Issue by davetapley** [ansible-collections/community.windows#334]
##### SUMMARY
Add `subfolder` parameter to [`win_unzip`](https://docs.ansible.com/ansible/latest/collections/community/windows/win_unzip_module.html#parameters).

When present only corresponding subfolder in the archive would be extracted to the given`dest` param.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`win_unzip`

##### ADDITIONAL INFORMATION

I can get a `.zip` of a full repo from GitHub (e.g. https://github.com/pyenv-win/pyenv-win/archive/refs/tags/v2.64.11.zip),
but if I only want to copy one subfolder (e.g. https://github.com/pyenv-win/pyenv-win/tree/v2.64.11/pyenv-win),
then I have to unzip to `%TEMP%`, manually copy, and manually clean up temp.

```yaml
    - name: Download pyenv-win
      ansible.windows.win_get_url:
        url: https://github.com/pyenv-win/pyenv-win/archive/refs/tags/v2.64.11.zip
        dest: '%TEMP%\pyenv-win.zip'

    - name: Extract pyenv-win
      community.windows.win_unzip:
        src: '%TEMP%\pyenv-win.zip'
        dest: 'C:\'
        subfolder: `pyenv-win`
        delete_archive: yes
```

⬆️ would extract https://github.com/pyenv-win/pyenv-win/tree/v2.64.11/pyenv-win to `C:\pyenv-win`.
