### ISSUE TITLE
win_shortcut - cant use arguments on executables

### ISSUE THREAD

**Issue by Daskan** [ansible-collections/community.windows#338]
##### SUMMARY
Using arguments (eg. '/c' or '<path_to_bat_file>') when src points to an executable will fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_shortcut

##### ANSIBLE VERSION

```
ansible 2.10.11
  config file = /home/xxx/ansible/client-playbooks-xxx/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.9/site-packages/ansible
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: created shortcut on Public Desktop
  community.windows.win_shortcut:
    dest: '{{ windows_desktop_dir }}\xxx.lnk'
    src: 'cmd.exe /c <path_to_bat_file>'
```

##### EXPECTED RESULTS

Defining Arguments in shortcuts should not cause problems.

##### ACTUAL RESULTS

```paste below
The full traceback is:
Der Wert liegt außerhalb des erwarteten Bereichs.
In Zeile:301 Zeichen:17
+                 $ShortCut.TargetPath = $src
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException

ScriptStackTrace:
bei <ScriptBlock>, <Keine Datei>: Zeile 301

System.ArgumentException: Der Wert liegt außerhalb des erwarteten Bereichs.
   bei System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
   bei CallSite.Target(Closure , CallSite , ComObject , Object )
   bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   bei System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   bei System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
fatal: [xxx.ad.xxx.de]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Der Wert liegt außerhalb des erwarteten Bereichs."
}
```

**Comment by jborean93** [comment]
You are meant to use `src` as the target executable only and then the `arguments` as the arguments for that shortcut, in your case it's:

```yaml
- name: created shortcut on Public Desktop
  community.windows.win_shortcut:
    dest: '{{ windows_desktop_dir }}\xxx.lnk'
    src: cmd.exe
    arguments: /c <path_to_bat_file>
```
