### ISSUE TITLE
win_psmodule needs to address -AcceptLicense parameter

### ISSUE THREAD

**Issue by ghost** [ansible-collections/community.windows#340]
##### SUMMARY

Support the AcceptLicense parameter for the Install-Module powershell cmdlet used by win_psmodule's Install-PsModule function.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_psmodule -> Function Install-PsModule

##### ADDITIONAL INFORMATION

There are some PowerShell modules that require the -AcceptLicense parameter to be passed to Install/Update-Module. For example, the HPCMSL module has a dependent module HP.Private that will not install without passing this parameter and returns an error.

This could be handled by adding an optional parameter to the win_psmodule, or by automatically applying it in the Install-PsModule function. I think best practice should be to add it as a boolean option to win_psmodule and default to false. This would be consistent retroactively with existing playbooks, and would help document when the parameter is required.

```yaml
- community.windows.win_psmodule:
    name: HPCMSL
    state: latest
    acceptlicense: true
```

**Comment by briantist** [comment]
Some more relevant info:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-license-acceptance?view=powershell-5.1

**Comment by davidsampson-hv** [comment]
This has caused a breaking change as not all PS modules accept the -acceptlicense parameter such as the FailoverClusterDSC module.

**Comment by thewriteway** [comment]
I still get a parameter error on when trying to execute the module.

I see in your example  its listed as acceptlicense and not accept_license , was that a typo?

**Comment by y-melo** [comment]
I was getting the same error, I had to add `skip_publishe_check: true`, not sure if is about the security of using this but it worked:
```yaml
- name: Install Nuget (for Pscx)
  win_psmodule:
    name: NuGet
    accept_license: true
    skip_publisher_check: true
    state: present
```
