### ISSUE TITLE
Add credential support to win_iis_virtualdirectory

### ISSUE THREAD

**Issue by nnstt1** [ansible-collections/community.windows#346]
##### SUMMARY

Add the ability to manage credential for IIS virtual directory using the `win_iis_virtualdirectory` module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_iis_virtualdirectory

##### ADDITIONAL INFORMATION

`win_iis_virtualdirectory` module does not have the ability to manage credential for IIS virtual directory.
Add the following parameters to the "win_iis_virtualdirectory" module to enable management of credential for virtual directory.

- connect_as
- username (Required if connect_as is specific_user)
- password (Required if connect_as is specific_user)

```yaml
- name: Create a virtual directory with 'pass-through' authentication
  community.windows.win_iis_virtualdirectory:
    name: somedirectory
    site: somesite
    state: present
    physical_path: C:\virtualdirectory\some
    connect_as: pass_through

- name: Create a virtual directory with 'specific user'
  community.windows.win_iis_virtualdirectory:
    name: somedirectory
    site: somesite
    state: present
    physical_path: C:\virtualdirectory\some
    connect_as: specific_user
    username: USERNAME
    password: PASSWORD
```
