### ISSUE TITLE
Request to add valuequeries as an additional option for the win_scheduled_task module under the type: event 

### ISSUE THREAD

**Issue by odtwawp** [ansible-collections/community.windows#351]
##### SUMMARY
Would like to have the ability to add ValueQueries as an option for win_scheduled_tasks module when chosing the type: event

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.windows.win_scheduled_task

##### ADDITIONAL INFORMATION
As of right now when you are using type event and a subscription, you do not currently have the ability to add valuequeuries 
an example of an xml output of a scheduled task that uses valuequeueries 
  <Triggers>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Microsoft-Windows-WAS'] and EventID=5011]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;**</Subscription>
      ****<ValueQueries>
        <Value name="eventChannel">Event/System/Channel</Value>
        <Value name="eventRecordID">Event/System/EventRecordID</Value>
        <Value name="eventSeverity">Event/System/Level</Value>
      </ValueQueries>****
    </EventTrigger>
  </Triggers>

```yaml
    - name: Create Event Task 
      community.windows.win_scheduled_task: 
        type: event
        subscription: <QueryList><Query Id="0" Path="System"><Select Path="System">*[System[Provider[@Name='Microsoft-Windows-WAS'] and EventID=5011]]</Select></Query></QueryList><valuequeries><value
        valuequeries: 
          - name: eventChannel
            value: Event/System/Channel
          - name: eventRecordID
            value: Event/System/EventRecordID
          - name: eventSeverity
            value: Event/System/Level
        actions: 
         - path: powershell
           working_directory: "{{icis_disk_config.name}}:/script"
           arguments: .\EventTriggerScript.ps1 -eventRecordID $(eventRecordID) -eventChannel $(eventChannel)
```
