### ISSUE TITLE
win_domain_user: Unable to pass extra variable (list) from AAP tower

### ISSUE THREAD

**Issue by draganmudric** [ansible-collections/community.windows#354]
##### SUMMARY

When creating domain user over win_domain_user I am not able to pass "groups" variable from the AAP tower. Here is my conf:

```
win_domain_user:
    name: "{{ user }}"
    firstname: "{{ firstname }}"
    surname: "{{ surname }}"
    password: "{{ password}}"
    groups: "{{ groups }}"
```

I can successfully pass all variables from the tower expect groups. Here is an error:

"msg": "Get-AnsibleParam: Parameter 'groups' is not a YAML list."

In the template on the AAP tower this is the variable I am trying to pass:

```
user: kita
firstname: Kita
surname: Unis
password: xxxxx
groups:
  - Domain Admins
  - Key Admins
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_user

##### ANSIBLE VERSION

`Ansible Automation Platform 4.0.0 `

##### CONFIGURATION

In the playbook:
```
win_domain_user:
    name: "{{ user }}"
    firstname: "{{ firstname }}"
    surname: "{{ surname }}"
    password: "{{ password}}"
    groups: "{{ groups }}"
```

Extra vars on the template in AAP tower:

```
user: kita
firstname: Kita
surname: Unis
password: xxxxx
groups:
  - Domain Admins
  - Key Admins
```

##### OS / ENVIRONMENT
Windows 2019

##### STEPS TO REPRODUCE

Create a user and try to pass a variable for group membership. Variable should be a list.
