### ISSUE TITLE
Manage group managed service accounts

### ISSUE THREAD

**Issue by alehaa** [ansible-collections/community.windows#359]
##### SUMMARY

Similar to `win_domain_user` and `win_domain_computer`, a new module to manage group managed service accounts (gMSA) would be nice (e.g. `win_domain_gmsa`). To install the gMSA to the machine, an additonal module like `win_install_gmsa` would be required.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Existing PowerShell modules:
* [New-ADServiceAccount](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount)
* [Install-ADServiceAccount](https://docs.microsoft.com/en-us/powershell/module/activedirectory/install-adserviceaccount?view=windowsserver2022-ps)

##### ADDITIONAL INFORMATION

```yaml
- name: Add database group managed service account
  community.windows.win_domain_gmsa:
    name: gmsa-database
    dns: database.contoso.com
    spn:
      - MSSQLSVC/database.contoso.com
    machine:
      - db-srv-a
      - db-srv-b
    state: present
  run_once: yes
```

```yaml
- name: Install group managed service account
  community.windows.win_install_gmsa:
    name: gmsa-database
    state: present
```
