### ISSUE TITLE
Can not add user to Organizational Unit

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/community.windows#367]
Hello! Thanks for community.windows

##### SUMMARY
win_domain_user can not add user to ou

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_user

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.11.1
```

##### COLLECTION VERSION
```paste below
Collection        Version
----------------- -------
ansible.windows   1.9.0
community.windows 1.9.0
```

##### CONFIGURATION
```paste below
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-core in version
 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/home/user/github/yc-terraform-examples/16-gitlab-active-directory-by-ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_STDOUT_CALLBACK(/home/user/github/yc-terraform-examples/16-gitlab-active-directory-by-ansible/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/home/user/github/yc-terraform-examples/16-gitlab-active-directory-by-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 20.04 where run ansible
Windows 2022 server

##### STEPS TO REPRODUCE
```yaml
- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc
  tasks:
    - name: Ensure user gitlab_ldap_sync is present
      community.windows.win_domain_user:
        name: gitlab_ldap_sync
        password: "{{ pswd_gitlab_ldap_sync }}"
        state: present
        path: cn=Users,dc=ad,dc=domain,dc=test
    - name: Ensure OU Gitlab Users is present
      community.windows.win_domain_ou:
        name: GitlabUsers
        path: dc=ad,dc=domain,dc=test
        state: present
    - name: Ensure user test_user_in_pdc is present
      community.windows.win_domain_user:
        name: test_user_in_pdc
        password: "{{ pswd_test_user_in_pdc }}"
        state: present
        path: ou=GitlabUsers,dc=ad,dc=domain,dc=test
```

##### EXPECTED RESULTS
 add user to ou

##### ACTUAL RESULTS
```paste below
TASK [Ensure OU Gitlab Users is present] ***********************************************************************************************************************************************
task path: /home/user/github/yc-terraform-examples/16-gitlab-active-directory-by-ansible/playbook.yml:13
changed: [dc2022] => changed=true
  invocation:
    module_args:
      domain_password: null
      domain_server: null
      domain_username: null
      filter: '*'
      name: GitlabUsers
      path: dc=ad,dc=domain,dc=test
      properties: null
      protected: false
      recursive: false
      state: present
  ou: null
  path: dc=ad,dc=domain,dc=test
Friday 18 March 2022  12:39:31 +0600 (0:00:02.123)       0:00:07.402 **********
Using module file /home/user/.ansible/collections/ansible_collections/community/windows/plugins/modules/win_domain_user.ps1
Pipelining is enabled.
<51.250.37.161> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 51.250.37.161
EXEC (via pipeline wrapper)

TASK [Ensure user test_user_in_pdc is present] *****************************************************************************************************************************************
task path: /home/user/github/yc-terraform-examples/16-gitlab-active-directory-by-ansible/playbook.yml:18
changed: [dc2022] => changed=true
  account_locked: false
  city: null
  company: null
  country: null
  created: false
  description: null
  distinguished_name: CN=test_user_in_pdc,DC=ad,DC=domain,DC=test
  email: null
  enabled: true
  firstname: null
  groups: CN=Domain Users,CN=Users,DC=ad,DC=domain,DC=test
  msg: User 'test_user_in_pdc' is present
  name: test_user_in_pdc
  password_expired: false
  password_never_expires: false
  password_updated: true
  postal_code: null
  sam_account_name: test_user_in_pdc
  sid: S-1-5-21-443304750-2951101722-1488002471-1107
  state: present
  state_province: null
  street: null
  surname: null
  upn: null
  user_cannot_change_password: false
META: ran handlers
META: ran handlers
```

![image](https://user-images.githubusercontent.com/10828883/158951647-ebfc61ce-befc-44b1-a5fb-b85a63edf379.png)

**Comment by patsevanton** [comment]
How correct add user to OU ?

**Comment by patsevanton** [comment]
Sorry.
May be i create incorrect playbook.
Work playbook:
```
- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc
  post_tasks:
    - name: Ensure user gitlab_ldap_sync is present
      community.windows.win_domain_user:
        name: gitlab_ldap_sync
        password: "{{ pswd_gitlab_ldap_sync }}"
        state: present
        path: cn=Users,dc=ad,dc=domain,dc=test
    - name: Ensure OU Gitlab Users is present
      community.windows.win_domain_ou:
        name: GitlabUsers
        path: dc=ad,dc=domain,dc=test
        state: present
    - name: Ensure user test_user_in_pdc is present
      community.windows.win_domain_user:
        name: test_user_in_pdc
        password: "{{ pswd_test_user_in_pdc }}"
        state: present
        path: ou=GitlabUsers,dc=ad,dc=domain,dc=test
```

![image](https://user-images.githubusercontent.com/10828883/159007171-95667345-63da-4721-97d5-2b07784e182d.png)
