### ISSUE TITLE
win_audit_rule cannot see path of 'HKU:\.Default' 

### ISSUE THREAD

**Issue by andrewcapuano07** [ansible-collections/community.windows#388]
##### SUMMARY
Hi Team,

Please see my below playbook, which fails to see a newly created virtual PS Drive and execute the creation of a new win_audit_rule on the HKU drive. It claims that the path is invalid, however ansible can register a variable for it and spit out the info relating to it. I believe that this must be a bug with the module.

It almost appears to be similar to the following issue with win_reg_stat that was fixed: https://github.com/ansible/ansible/issues/59337

https://github.com/ansible/ansible/pull/59359  <-- explanation that a typo caused the error for users

That was solved via Ansible team's pull req: https://github.com/ansible/ansible/pull/59359/commits/7f7c5d856047462d61cbaace04768879e3241ba8 

Is there some chance that the same happened with this community module? 

The debug seemed to show that our path exists, but the community.windows.win_audit_rule cant see it! It must be something syntactically or a bug. Please let us know what you think.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_audit_rule

##### ANSIBLE VERSION

```paste below
ansible 2.9.15

```

##### COLLECTION VERSION

```
community.windows:1.9.0

```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['community.general.sumologic']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

The server we are targeting has Windows 2016 

##### STEPS TO REPRODUCE

Please try using the playbook code that I pasted above in my Summary. 

```yaml

---
- name: Update Audit Rules on Windows Server
  hosts: "{{server}}"
  gather_facts: false

  tasks:

  - name: Register Variable to see if HKU:\DEFAULT Exists. Ignore Errors if it does not exist
    win_reg_stat:
      path: HKU:\.DEFAULT
    register: hku_variable
    ignore_errors: yes

  - name: Print out hku_variable
    debug:
      msg: "{{ hku_variable }}"
    when: hku_variable is defined

  - name: Add PS Path for HKU if it does not already exist
    win_shell: New-PSDrive -PSProvider Registry -Name HKU -Root HKEY_USERS
    when: hku_variable is not defined

  - name: Create Audit Rule at HKU:\.DEFAULT
    community.windows.win_audit_rule:
      path: 'HKEY_USERS\.DEFAULT'
      user: Everyone
      rights: SetValue,CreateSubKey,Delete,ChangePermissions,TakeOwnership
      audit_flags: success
      propagation_flags: None
      inheritance_flags: ContainerInherit,ObjectInherit
    
  
```

##### EXPECTED RESULTS

In the task "Create Audit Rule at HKU:\.DEFAULT", I want to see "changed" for the server, and that the audit rule is created at the newly created PS-Drive (HKU). For some reason, the module is not recognizing the new drive, although Ansible can register a variable for the drive and spit out the correct information about it. 

##### ACTUAL RESULTS

TASK [Register Variable to see if HKU:\DEFAULT Exists. Ignore Errors if it does not exist] ***
ok: [MY_SERVER]

TASK [Print out hku_variable] **************************************************
ok: [MY_SERVER] => {
    "msg": {
        "changed": false,
        "exists": true,
        "failed": false,
        "properties": {},
        "sub_keys": [
            "Control Panel",
            "Environment",
            "EUDC",
            "Keyboard Layout",
            "Printers",
            "Software",
            "System"
        ]
    }
}

TASK [Add PS Path for HKU if it does not already exist] ************************
skipping: [MY_SERVER]

TASK [Create Audit Rule at HKU:\.DEFAULT] **************************************
fatal: [MY_SERVER]: FAILED! => {"changed": false, "msg": "Get-AnsibleParam: Parameter 'path' has an invalid path 'HKU:\\.DEFAULT' specified."}

PLAY RECAP *********************************************************************
MY_SERVER               : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
