### ISSUE TITLE
win_dns_record: option to automatically create PTR record

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#41]
_From @senilio on Oct 18, 2019 10:47_

##### SUMMARY

When creating an A or AAAA record using the `win_dns_record` module, it would be nice to have the option to automatically create the "associated PTR record". This tick box is available in the DNS Manager GUI when manually creating an A record.

Having this option would basically cut my DNS definition dict in half, since I would't have to define all PTR's.

[DNS Manager GUI screenshot](https://i.imgur.com/YxO5hfO.png)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_dns_record

##### ADDITIONAL INFORMATION

Add a new boolean `ptr` to `win_dns_record`. 
Default value false, to stick to the current default behavior.
When true, the behavior should be the same as when ticking the box in the GUI.

```yaml
  - name: Create records
    win_dns_record:
      name: "{{ item.name }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      zone: "{{ item.zone }}"
      ptr: "{{ item.ptr }}"
    with_items: "{{ dns_records }}"
```

_Copied from original issue: ansible/ansible#63672_
