### ISSUE TITLE
win_psmodule fails to install the prerequisites due to absence of AllowClobber

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#42]
_From @maxnasonov on Oct 22, 2019 11:45_

##### SUMMARY
win_psmodule fails to install the prerequisites due to absence of AllowClobber

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_psmodule

##### ANSIBLE VERSION

```
ansible 2.8.6
  config file = None
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT
Windows Server 2019 Datacenter

##### STEPS TO REPRODUCE

```yaml
  - name: Add xExchange DSC module
    win_psmodule:
      name: xExchange
      repository: PSGallery
      required_version: 1.29.0.0
      state: present
```

##### EXPECTED RESULTS
Successful install of xExchange module

##### ACTUAL RESULTS
```
The following commands are already available on this system:'Find-Package,Install-Package,Uninstall-Package'. This module 'PackageManagement' may override the existing commands. If you still want to install this module 'PackageManagement', use -AllowClobber parameter.
```

_Copied from original issue: ansible/ansible#63780_
