### ISSUE TITLE
```Get-HotfixMetadataFromKB``` fails to check package description

### ISSUE THREAD

**Issue by ntran46** [ansible-collections/community.windows#421]
##### SUMMARY
```hotfix_kb``` does not work with the KB package whose name is specified in the package description. 
The function always returns with the error ```"failed to get DISM package from KB, to continue specify hotfix_identifier instead"```

Manually running the  win_hotfix.ps1 file, I see variable ```$metadata``` at line 151 seems not to be defined but gets called. Even though there is a valid result returned from the loop, it cannot pass line 151 (**if statement**). Might it be ```$raw_metadata``` or ```$identifier``` instead?
```
foreach ($package in $packages) {
            $raw_metadata = Get-HotfixMetadataFromName -name $package.PackageName
            if ($raw_metadata.kb -eq $kb) {
                $identifier = $raw_metadata
                break
            }
        }

if ($null -eq $metadata) {
            Fail-Json $result "failed to get DISM package from KB, to continue specify hotfix_identifier instead"
        }
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```win_hotfix```

##### ANSIBLE VERSION

```paste below
2.9.x
```

##### COLLECTION VERSION

```paste below
NA
```

##### CONFIGURATION

```paste below
NA
```

##### OS / ENVIRONMENT

Windows 10 and Windows servers 2012 + 2016

##### STEPS TO REPRODUCE

Windows servers 2016:
Run ```dism /online /get-packages /format:table``` and get any package that does not contain the KB number in its name but in its description. For example
```
Package information:

Package Identity : Package_for_RollupFix~31bf3856ad364e35~amd64~~14393.5246.1.6
Applicable : Yes
Copyright : Microsoft Corporation
Company : Microsoft Corporation
Creation Time :
Description : Fix for KB5015808
Install Client : WindowsUpdateAgent
Install Package Name : Package_for_RollupFix~31bf3856ad364e35~amd64~~14393.5246.1.6.mum
Install Time : 7/13/2022 10:03 AM
Last Update Time :
Name : default
Product Name : Package_for_RollupFix
Product Version :
Release Type : Security Update
Restart Required : Possible
Support Information : https://support.microsoft.com/help/5015808
State : Installed
Completely offline capable : No
Self servicing package : No
Capability Identity :

```

```yaml
- name: "Install Windows ADK with DISM"
  win_chocolatey:
    name: windows-adk-deploy
    state: present
    version: 10.0.17134.0
    install_args: /features OptionId.DeploymentTools

- name: "Verify Windows PATH contains DISM"
  win_path:
    scope: machine
    state: present
    elements: "C:\\Program Files (x86)\\Windows Kits\\10\\Assessment and Deployment Kit\\Deployment Tools\\amd64\\DISM"

- name: "Uninstall hotfix KB5015808"
  win_hotfix:
    hotfix_kb: "KB5015808"
    state: absent
  become_method: runas
  register: hotfix_uninstall
```

##### EXPECTED RESULTS

Package got removed

##### ACTUAL RESULTS

```paste below
fatal: [******]: FAILED! => changed=false 
 msg: failed to get DISM package from KB, to continue specify hotfix_identifier instead
 reboot_required: false
```
