### ISSUE TITLE
win_psmodule error: A parameter cannot be found that matches parameter name 'AcceptLicense' in 1.11.0

### ISSUE THREAD

**Issue by shadowink** [ansible-collections/community.windows#424]
##### SUMMARY
In 1.11.0 win_psmodule is throwing the error:Problems installing PSSlack module: A parameter cannot be found that matches parameter name 'AcceptLicense'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_psmodule

##### ANSIBLE VERSION

```paste below
2.11.6
```

##### COLLECTION VERSION

```paste below
1.11.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible running on a Win10 20h2 VM via a packer build.

##### STEPS TO REPRODUCE

```yaml
- name: Add Powershell Slack module
  community.windows.win_psmodule:
    name: PSSlack
    state: present

```

##### EXPECTED RESULTS

{
  "changed": true,
  "nuget_changed": true,
  "output": "Module PSSlack installed",
  "repository_changed": false
}

##### ACTUAL RESULTS

```paste below
"msg": "Problems installing PSSlack module: A parameter cannot be found that matches parameter name 'AcceptLicense'."
```
I downgrading the collection to 1.10.0 and the error did not occur.
