### ISSUE TITLE
Win_scheuled_task: Username parameter is unable to find domain when logon type is password

### ISSUE THREAD

**Issue by ashorie-clgx** [ansible-collections/community.windows#444]
##### SUMMARY
Username parameter is unable to find domain when logon type is password

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Win_scheduled_task

##### ANSIBLE VERSION
2.9

```

##### COLLECTION VERSION
1.11.0 
```paste below

```

##### CONFIGURATION
ansible-v2.9
```

##### OS / ENVIRONMENT
Windows server 2016


##### STEPS TO REPRODUCE
logon_type should be "password" and tried username(with DOMAIN/User and also FQDN) and password and I get below error everytime mentioned in actual results
```- name: Create scheduled task to run batch file RMBS 2.0 v4 
  win_scheduled_task:
    name: "{{ RMBS_scheduled_task_name }}"
    description: Run batch file for RMBS data collection
    actions:
    - path: "{{ RMBS_task_folder }}\\pj_rmbs_v4.bat"
    triggers:
    - type: weekly
      start_boundary: '2022-09-26T17:15:00'
      days_of_week:
        - monday 
        - tuesday
        - wednesday
        - thursday
        - friday
    logon_type: password
## both ways Username does not acccept domain with and without quotes
    username: isc\ashorie@corelogic.com
#   username: isc\ashorie 
    password: "{{ domain-service-account-password }}"
    run_level: highest
    state: present
    enabled: yes
    allow_demand_start: yes

```

##### ACTUAL RESULTS
"msg": "The task includes an option with an undefined variable. The error was: 'domain' is undefined\n\nThe error appears to be in '/home/jenkins/agent/workspace/minal-server_terminal-server-dev/terminal-server/ansible/roles/terminal-server/tasks/misc.yml': line 181, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create scheduled task to run batch file RMBS 2.0 v4\n  ^ here\n"

```paste below

```
