### ISSUE TITLE
Add password to win_unzip module

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#47]
_From @moleszek on Feb 11, 2020 16:15_

##### SUMMARY
According to Ansible documentation, `win_unzip` module does not support the `password` parameter.
This makes ansible unable to unpack the `.zip` file, which is password protected.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_unzip:
  password: "password123"

##### ADDITIONAL INFORMATION
Adding this feature will solve problems with unpacking password-protected files.

```yaml
- name: Unzip zip file
  win_unzip:
    src: C:\test\file.zip
    dest: C:\test\unpacked\
    recurse: no
    password: "password123"
```

_Copied from original issue: ansible/ansible#67308_
