### ISSUE TITLE
Unexpected string added when using community.windows.win_xml

### ISSUE THREAD

**Issue by sefalbe** [ansible-collections/community.windows#470]
##### SUMMARY

I'm working with ansible to replace some values in web.config file, I'm using `community.windows.win_xml` module.

- name: Change webconfig value
      community.windows.win_xml:
        path: "{{ web_projects_path }}\\Web.config"
        xpath: //configuration/connectionStrings/add[@name="EntityConn"]
        attribute: connectionString
        fragment: '{{ EntityConn }}'
        type: attribute
        state: present

As you can see, I use _**EntityConn**_ variable to set value: 

```
vars:
  EntityConn: 'metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;'

```
The win_xml module works but adds _**amp**_ word when find `&quot` having as result `&amp;quot`, and the final output:

```
<add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&amp;quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated 
Security=True;MultipleActiveResultSets=True&amp;quot" providerName="System.Data.EntityClient" />
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_xml

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.7]
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.10.0

# /home/user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.1

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.1
```

##### OS / ENVIRONMENT

Linux 4ansible 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml (paste below)

- name: Windows Feature
  hosts: Windows2016
  vars:
    web_projects_path: "C:\\Path\\To\\Project"
    EntityConn: 'metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;'

  tasks:
    - name: Print values
      ansible.builtin.debug:
        msg: MMSPRP5Entities {{ EntityConn}}

    - name: Change webconfig value
      community.windows.win_xml:
        path: "{{ web_projects_path }}\\Web.config"
        xpath: //configuration/connectionStrings/add[@name="EntityConn"]
        attribute: connectionString
        fragment: '{{ EntityConn }}'
        type: attribute
        state: present
```
And here my Web.config file:
```
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="" providerName="System.Data.EntityClient"/>
  </connectionStrings>
</configuration>
```

##### EXPECTED RESULTS

The expected result is the connection string without _**amp**_ string
```
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;" providerName="System.Data.EntityClient"/>
  </connectionStrings>
</configuration>
```

##### ACTUAL RESULTS

```console
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&amp;quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated 
Security=True;MultipleActiveResultSets=True&amp;quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
</configuration>
```
