### ISSUE TITLE
add ObjectGUID field as a return field for win_domain_user module

### ISSUE THREAD

**Issue by tdavison784** [ansible-collections/community.windows#473]
##### SUMMARY
Would like to have the win_domain_user module also return ObjectGUID of a user as another data field to interact with. We have a few different scenarios were the use of that field is needed, and rather then writing one off win_shell inline powershell commands it would be nice to formalize use with win_domain_user and be able to view the ObjectGUID as a returned element after the task has completed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_domain_user

##### ADDITIONAL INFORMATION
In the module return data, add ObjectGUID as one of the returned elements

```yaml
- name: "Query to gather user details"
  win_domain_user:
    state: "query"
    name: "testUser"
    domain_username: "domainAdmin"
    domain_password: "domainPassword"
  register: user_data

- name: "debug ObjectGUID for testUser"
  debug: msg="{{  user_data.objectguid }}"
    
```
