### ISSUE TITLE
Request to add display_name field to win_domain_user

### ISSUE THREAD

**Issue by Daniel-Sanchez-Fabregas** [ansible-collections/community.windows#477]
##### SUMMARY

Currently `win_domain_user` don't have a field to modify the user display name, my request to add said `display_name` field to `win_domain_user`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_domain_user

##### ADDITIONAL INFORMATION

The `display_name` field should be used to specify the user display name.

```yaml
- name: Create User Hana Lytx
  win_domain_user:
    name: hana
    upn: hana@ansible.test
    firstname: Hana
    surname: Lytx
    display_name: Hana Lytx
    company: HelpMeExitVi Inc.
    password: h@nAlyTx18!X
    state: present
    groups:
      - Domain Admins
    street: 123 TechTok St.
    city: Sysengineer
    state_province: OH
    postal_code: 12345
    country: US
    attributes:
      telephoneNumber: 555-123456
    update_password: when_changed
    password_never_expires: true
```
