### ISSUE TITLE
Support access_path as alternative to drive_letter in `win_partition`

### ISSUE THREAD

**Issue by jantari** [ansible-collections/community.windows#490]
##### SUMMARY
Support NTFS Access path mounting for partitions as an alternative to DOS-style drive letters. For example hrough [Add-PartitionAccessPath](vhttps://learn.microsoft.com/en-us/powershell/module/storage/add-partitionaccesspath?view=windowsserver2022-ps).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_partition

##### ADDITIONAL INFORMATION
Currently `community.windows.win_partition` can only assign DOS-style drive letters to partitions.

However, drive letters are difficult and inconsistent to automate - depending on how many CDROM drives a VM has, an arbitrary number of letters may be taken and they are difficult to shuffle around.

Replacing an older server with a new one that has slightly different disk / optical drive configuration can completely foil any attempts to reuse drive letter assignments from the old machine etc., it's just a hassle and I really don't want to use drive letters for anything ever.

For example the task:
```yaml
    - name: Create partition
      community.windows.win_partition:
        disk_number: '{{ (_find_disk_command.stdout | from_json())[0].Index }}'
        partition_size: -1 # maximum available size
        drive_letter: E
```

would become:

```yaml
    - name: Create partition
      community.windows.win_partition:
        disk_number: '{{ (_find_disk_command.stdout | from_json())[0].Index }}'
        partition_size: -1 # maximum available size
        access_path: '{{ ansible_env.SystemDrive }}\WhateverMountPoint'
```

An alternative that works today, and I've used in the past, is to do it through DSC - but native support directly in `win_partition` would be far nicer:

```yaml
    - name: Make sure mount-directory exists
      ansible.windows.win_file:
        path: '{{ ansible_env.SystemDrive }}\WhateverMountPoint'
        state: directory
    
    - name: Install StorageDsc DSC module
      community.windows.win_psmodule:
        name: StorageDsc
        state: present
    
    - name: Create and format partition
      ansible.windows.win_dsc:
        resource_name: DiskAccessPath
        DiskIdType: Number
        DiskId: '{{ (_find_disk_command.stdout | from_json())[0].Index }}'
        AccessPath: '{{ ansible_env.SystemDrive }}\WhateverMountPoint'
        FSFormat: NTFS
```

Thanks!!
