### ISSUE TITLE
`community.windows.win_credential` fails with "Failed to access the user's credential store, run the module with become"

### ISSUE THREAD

**Issue by nemonik** [ansible-collections/community.windows#497]
##### SUMMARY

```
- name: Create credential
  community.windows.win_credential:
    name: 127.0.0.1
    type: generic_password
    username: Administrator
    secret: "Ch@ng3M3!"
    state: present
```

Results in 

```
The full traceback is:
Exception calling "GetCredential" with "2" argument(s): "Failed to access the user's credential store, run the module with become"
At line:578 char:1
+ $existing_credential = [Ansible.CredentialManager.Credential]::GetCre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidOperationException

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 578
fatal: [IP]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"GetCredential\" with \"2\" argument(s): \"Failed to access the user's credential store, run the module with become\""
}

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.windows.win_credential

##### ANSIBLE VERSION

```
➜  ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/home/nemonik.linux/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nemonik.linux/.cache/pypoetry/virtualenvs/something-rnn__9Px-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nemonik.linux/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nemonik.linux/.cache/pypoetry/virtualenvs/something-rnn__9Px-py3.10/bin/ansible
  python version = 3.10.7 (main, Jan  5 2023, 00:11:54) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/nemonik.linux/.cache/pypoetry/virtualenvs/something-rnn__9Px-py3.10/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.0

# /home/nemonik.linux/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.12.0
```

##### CONFIGURATION

```
returned nothing
```

##### OS / ENVIRONMENT

```
Linux lima-mep 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

##### STEPS TO REPRODUCE

```
- name: Create credential
  community.windows.win_credential:
    name: 127.0.0.1
    type: generic_password
    username: Administrator
    secret: "Ch@ng3M3!"
    state: present
```

##### EXPECTED RESULTS

To create the credential

##### ACTUAL RESULTS

```
The full traceback is:
Exception calling "GetCredential" with "2" argument(s): "Failed to access the user's credential store, run the module with become"
At line:578 char:1
+ $existing_credential = [Ansible.CredentialManager.Credential]::GetCre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidOperationException

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 578
fatal: [IP]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"GetCredential\" with \"2\" argument(s): \"Failed to access the user's credential store, run the module with become\""
```   

But 

```powershell
cmdkey /generic:127.0.0.1 /user:"Administrator" /pass:"Ch@ngeM3!" 
```

works.
