### ISSUE TITLE
Adding AD group to other AD group not working with win_domain_group_membership

### ISSUE THREAD

**Issue by mesiq** [ansible-collections/community.windows#518]
##### SUMMARY

when using state: present for adding an AD group into another AD the module fails with:
```
failed: [XXX-> XXX] (item=USR) => {"ansible_loop_var": "item", "changed": false, "item": "USR", "msg": "Get-AnsibleParam: Argument state needs to be one of domain,workgroup but was present."}
failed: [XXX-> XXX] (item=CON) => {"ansible_loop_var": "item", "changed": false, "item": "CON", "msg": "Get-AnsibleParam: Argument state needs to be one of domain,workgroup but was present."}
```
The  documentation used: [docu](https://docs.ansible.com/ansible/devel/collections/community/windows/win_domain_group_membership_module.html#ansible-collections-community-windows-win-domain-group-membership-module)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_group_membership

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.2]
  python version = 3.8.14 (default, Sep 19 2022, 09:47:48) [GCC 9.1.1 20190605 (Red Hat 9.1.1-2)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.windows 1.13.0
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/opt/ansible/ansible.cfg) = True
DEFAULT_FORKS(/opt/ansible/ansible.cfg) = 100
DEFAULT_TIMEOUT(/opt/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault
DEPRECATION_WARNINGS(/opt/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/opt/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/opt/ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/opt/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

ansible server: Red Hat Enterprise Linux 7.9
host server: Windows 2012R2

##### STEPS TO REPRODUCE

```yaml
- name: "Ensure Access groups are members of Resource groups"
  win_domain_membership:
    name: "R-A-{{ item }}"
    members:
    - "A-A-{{ item }}"
    state: present
  delegate_to: "{{ domain_controlers[0] }}"
  ignore_errors: true
  ignore_unreachable: true
  loop:
  - CON
  - USR
```
Note: domain_controllers is the dict with AD DCs where powershell AD module is installed - other modules - e.g. win_domain_group is working normally

##### EXPECTED RESULTS

Group is membership is added

##### ACTUAL RESULTS

```paste below
failed: [XXX-> XXX] (item=USR) => {"ansible_loop_var": "item", "changed": false, "item": "USR", "msg": "Get-AnsibleParam: Argument state needs to be one of domain,workgroup but was present."}
failed: [XXX-> XXX] (item=CON) => {"ansible_loop_var": "item", "changed": false, "item": "CON", "msg": "Get-AnsibleParam: Argument state needs to be one of domain,workgroup but was present."}
```
