### ISSUE TITLE
win_scheduled_task: RegisterTaskDefinition error using a trigger with start_boundary

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.windows#53]
_From @aventrax on Mar 13, 2020 10:38_

##### SUMMARY
When configuring a scheduled task using the win_scheduled_task module I got an error in case the trigger is set daily with a start_boundary using the format specified on the docs.
This tasks is part of one of my old roles and it was working with Ansible 2.8.5 but not with 2.9.6.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_scheduled_task tails

##### ANSIBLE VERSION
- 2.9.6

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS with ansible in a virtual  env

##### STEPS TO REPRODUCE

ansible-playbook -vvvv  mio.yml -l 172.16.8.176

```
--- 
- hosts: all 
  gather_facts: false

  tasks:

  - name: Configuring scheduled task to clean IIS tmp folder daily 
    win_scheduled_task:
      name: IISTmpCleaner
      description: Rimuove file temporanei piu' vecchi di 3 giorni
      actions:
      - path: C:\Windows\System32\forfiles.exe
        arguments: '/P C:\Windows\SysWOW64\inetsrv\tmp /S /D -3  /C "cmd /c if @isdir==FALSE del @file"'
      triggers:
      - type: daily
        start_boundary: '2017-10-09T01:39:00'
      username: SYSTEM
      run_level: highest
      state: present
      enabled: true

...
```

##### EXPECTED RESULTS
No errors at all, as of ansible 2.8.5

##### ACTUAL RESULTS

```
TASK [Configuring scheduled task to clean IIS tmp folder daily] ****************************************************************************************************************************************************************************task path: /home/matteo/Ansible/MEDarchiver/mio.yml:7
Using module file /opt/python-virtual-envs/default/lib/python3.6/site-packages/ansible/modules/windows/win_scheduled_task.ps1 
Pipelining is enabled.
<172.16.8.176> ESTABLISH WINRM CONNECTION FOR USER: auxonet\medadmin on PORT 5985 TO 172.16.8.176
EXEC (via pipeline wrapper) 
fatal: [172.16.8.176]: FAILED! => { 
    "changed": false,
    "msg": "failed to modify scheduled task: Exception calling \"RegisterTaskDefinition\" with \"6\" argument(s): \"(4,33):Date:2017-10-09T01.39.00\""
}
```

_Copied from original issue: ansible/ansible#68210_

**Comment by ShachafGoldstein** [comment]
can you please post verbose output? `-vvvv`

**Comment by Akasurde** [comment]
@aventrax can you please post verbose output? -vvvv

**Comment by aventrax** [comment]
```
$ ansible-playbook -vvvv -i inventories/production mio.yml -l 172.16.8.176 
ansible-playbook 2.9.6 
  config file = /home/userx/.ansible.cfg
  configured module search path = ['/home/userx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python-virtual-envs/default/lib/python3.6/site-packages/ansible
  executable location = /opt/python-virtual-envs/default/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Using /home/userx/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/userx/ansible/inventories/production/hosts.yaml as it did not pass its verify_file() method 
script declined parsing /home/userx/ansible/inventories/production/hosts.yaml as it did not pass its verify_file() method
Parsed /home/userx/ansible/inventories/production/hosts.yaml inventory source with yaml plugin 
Loading callback plugin default of type stdout, v2.0 from /opt/python-virtual-envs/default/lib/python3.6/site-packages/ansible/plugins/callback/default.py 
 
PLAYBOOK: mio.yml **************************************************************************************************************************************************************************************************************************
Positional arguments: mio.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
inventory: ('/home/userx/ansible/inventories/production',)
subset: 172.16.8.176
forks: 5
1 plays in mio.yml

PLAY [all] *********************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Configuring scheduled task to clean IIS tmp folder daily] ****************************************************************************************************************************************************************************
task path: /home/userx/ansible/mio.yml:7
Trying secret FileVaultSecret(filename='/home/userx/.vault_pass.txt') for vault_id=default
Trying secret FileVaultSecret(filename='/home/userx/.vault_pass.txt') for vault_id=default
Trying secret FileVaultSecret(filename='/home/userx/.vault_pass.txt') for vault_id=default
Using module file /opt/python-virtual-envs/default/lib/python3.6/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<172.16.8.176> ESTABLISH WINRM CONNECTION FOR USER: auxonet\medadmin on PORT 5985 TO 172.16.8.176
EXEC (via pipeline wrapper)
fatal: [172.16.8.176]: FAILED! => {
    "changed": false,
    "msg": "failed to modify scheduled task: Exception calling \"RegisterTaskDefinition\" with \"6\" argument(s): \"(4,33):Date:2017-10-09T01.39.00\""
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
172.16.8.176               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by ShachafGoldstein** [comment]
Can you please try using a date and time that aren't in the past?

**Comment by aventrax** [comment]
Tried. No difference.

Anyway, I tried this on a different inventory/host, both are Windows 2012R2 servers but on the new host I had no issues running the same playbook con Ansible 2.9.7. Same OS, same psversion, same locale... The only difference that I noticed is the ansible connection method (ntlm vs kerberos), kerberos on the working server, but I this this is not important at all.

Just to be clear and repeat. Ansible 2.8.5 has no issues on both servers.

**Comment by fpl-fi** [comment]
Is this issue still not fixed?

It is not possible to define daily tasks with a start boundary.

```yaml
- name: Install scheduled task
  community.windows.win_scheduled_task:
    name: TaskName
    description: ...
    path: \CustomPath
    username: ...$
    logon_type: password
    update_password: false
    triggers:
      - type: daily
        start_boundary: '2017-10-09T01:39:00'
        repetition:
          interval: PT15M
    actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: -ExecutionPolicy Unrestricted -NonInteractive -File "..."
```

Outputs (in ansible tower):

```
TASK [role : Install scheduled task] *****************************************
task path: /runner/project/roles/role/tasks/install_windows_sched_tasks.yaml:13
Using module file /usr/share/ansible/collections/ansible_collections/community/windows/plugins/modules/win_scheduled_task.ps1
Pipelining is enabled.
<windows_server> ESTABLISH WINRM CONNECTION FOR USER: ansible@domain on PORT 5986 TO windows_server
EXEC (via pipeline wrapper)
fatal: [windows_server]: FAILED! => {
    "changed": true,
    "msg": "failed to modify scheduled task: (4,33):Date:2017-10-09T01.39.00"
}
```
Error details:
```json
{
  "changed": true,
  "msg": "failed to modify scheduled task: (4,33):Date:2017-10-09T01.39.00",
  "_ansible_no_log": false
}
```

I am working around the issue with `type: registration` but this type of schedule seems to fail after some time.

**Comment by fpl-fi** [comment]
This issue is caused by regional settings.
I have added a workaround of setting regional formats to en-US before tasks modifying schedules.
```yaml
---
- name: Set the region format to English United States
  community.windows.win_region:
    format: en-US
  register: win_region_result
- name: Reboot if necessary
  ansible.windows.win_reboot:
  when: win_region_result.restart_required

...
```
----

I'd wager the issue is actually just time delimiter since date separators are not adjusted by windows thanks to being set here manually:

https://github.com/ansible-collections/community.windows/blob/aff2fabe528380a354b2c78f6499a7f83947df1b/plugins/modules/win_scheduled_task.ps1#L798C49-L798C84

Maybe it would be enough to set time format separator for running thread at the beginning of the script instead of having to rely on users always defaulting to en-US user format?

```powershell
$CurrentCulture = [System.Globalization.CultureInfo]::CurrentCulture
$CurrentCulture.DateTimeFormat.TimeSeparator = ":"
[System.Threading.Thread]::CurrentThread.CurrentCulture = $CurrentCulture
```
```powershell
> $date_value = '2017-10-09T01:39:00'
> Get-Date -Date $date_value -Format "yyyy-MM-dd'T'HH:mm:ssK"
2017-10-09T01.39.00

> $CurrentCulture = [System.Globalization.CultureInfo]::CurrentCulture
> $CurrentCulture.DateTimeFormat.TimeSeparator = ":"
> [System.Threading.Thread]::CurrentThread.CurrentCulture = $CurrentCulture

> Get-Date -Date $date_value -Format "yyyy-MM-dd'T'HH:mm:ssK"
2017-10-09T01:39:00
```

I would make a pull request to add this myself but I am not familiar with the public github etiquette, nor how to validate these modules prior to making changes, so it would be appreciated if someone could do that.
