### ISSUE TITLE
Allow configuring NSSM to preserve log files on service restart/crash

### ISSUE THREAD

**Issue by drfuzzyness** [ansible-collections/community.windows#536]
##### SUMMARY

It would be helpful if the `community.windows.win_nssm` module can expose NSSM's `AppStdoutCreationDisposition` and `AppStderrCreationDisposition` properties so that logs can be preserved when a service restarts. See "File Rotation Tab" on [the NSSM usage page](https://nssm.cc/usage) for a small amount of extra information.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`community.windows.win_nssm`

##### ADDITIONAL INFORMATION

This would pass an integer (2 or 4 are known valid options) directly to NSSM's service configuration. `AppStdoutCreationDisposition` and `AppStderrCreationDisposition` can be set independently, but follow similar logic. They should default to the current behavior of setting the -value to `2` (replace log files on restart).

Current behavior:
https://github.com/ansible-collections/community.windows/blob/03e3af7baf85c2b14e558d3b9f1659712a3c6891/plugins/modules/win_nssm.ps1#L494-L495

Proposed configuration example:

```yaml
tasks:
  - name: My Service
    community.windows.win_nssm:
      name: MyNssmService
      display_name: My NSSM Service
      application: C:\MyFolder\MyExecutable.exe
      app_directory: C:\MyFolder\
      arguments: --silent
      stdout_file: C:\MyFolder\Logs\stdout.log
      stderr_file: C:\MyFolder\Logs\stderr.log
      app_rotate_online: 1
      app_stdout_creation_disposition: 2 # replace file on every service restart
      app_stdout_creation_disposition: 4 # append to file instead of deleting file
      state: restarted
      app_environment:
        PORT: 3001
```
