### ISSUE TITLE
win_product_facts returning list instead of string

### ISSUE THREAD

**Issue by Yannik** [ansible-collections/community.windows#540]
##### SUMMARY
As far as my understanding goes, `win_product_facts` should provide information about the windows operating system licensing status. This is further supported by the [logic to retrieve the product key](https://github.com/ansible-collections/community.windows/blob/6b7254c2679dad9ca91d2891df5bc0aa3d4c4345/plugins/modules/win_product_facts.ps1#L23), which only results in one product key, the one of the windows operating system. Finally, the `returned facts` description also indicates that `ansible_os_license_edition`, `ansible_os_license_status` and `ansible_os_license_channel` should contain a string regarding the windows operating system licensing state.

However, I have noticed that when microsoft office is installed, `win_product_facts` actually sets `ansible_os_license_edition`, `ansible_os_license_status` and `ansible_os_license_channel` to an array which contains information about both windows and ms office.

Using the [examples from the module page](https://docs.ansible.com/ansible/latest/collections/community/windows/win_product_facts_module.html):

```
TASK [windows-activation : Display Windows edition] ************************************************
ok: [myhost] => 
  ansible_os_license_edition:
  - Windows(R), Professional edition
  - Office 16, Office16StandardVL_KMS_Client edition

TASK [windows-activation : Display Windows license status] *****************************************
ok: [myhost] => 
  ansible_os_license_status:
  - Licensed
  - Licensed
```

The reason for this is the `Get-CimInstance SoftwareLicensingProduct | Where-Object PartialProductKey` [command](https://github.com/ansible-collections/community.windows/blob/6b7254c2679dad9ca91d2891df5bc0aa3d4c4345/plugins/modules/win_product_facts.ps1#L81), which can return more than one result. It would be sensible to append a `Where-Object Name -match Windows` filter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_product_facts
