### ISSUE TITLE
Provide ability to create a DHCP Scope

### ISSUE THREAD

**Issue by DonBower** [ansible-collections/community.windows#552]
##### SUMMARY

While creating DHCP leases are a great feature, A zone is required to place them in.

##### ISSUE TYPE
- Feature Idea
Add a new module which will allow one to create the scope and set some default options.

##### COMPONENT NAME

I would suggest `win_dhcp_lease`

##### ADDITIONAL INFORMATION

```yaml
- name: Ensure DHCP reservation exists
  community.windows.win_dhcp_scope:
    type: (ipv4 | ipv6)
    start_ip: 192.168.1.1
    end_ip: 192.168.1.254
    scope_id: 192.168.1.0
    name: my_scope
    description: Testing Scope
    scope_options:
      - 003: 192.168.1.1
      - 005: [192.168.1.1, 192.168.1.2]
      - 015: mydomain.net
```
