### ISSUE TITLE
"The DISM PS module needs to be installed, this can be done through the windows-adk chocolately package"

### ISSUE THREAD

**Issue by garyneville** [ansible-collections/community.windows#557]
##### SUMMARY
Getting the message "The DISM PS module needs to be installed, this can be done through the windows-adk chocolately package" even when the module has been installed - using Chocolatey. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

``` 
2.16.3
```

##### COLLECTION VERSION

```
community.windows 2.1.0  

```

##### CONFIGURATION

```
ANSIBLE_HOME(env: ANSIBLE_HOME) = /home/ansibleadmin/ansible
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 30
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/ansibleadmin/ansible/logs/ansible.log
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'vmware_vm_inventory']

```

##### STEPS TO REPRODUCE
Other info - the suggested version of windows-adk is no longer available on Chocolatey (
```yaml
- name: Install Windows ADK with DISM for Server 2008 R2
  chocolatey.chocolatey.win_chocolatey:
    name: windows-adk
    version: 8.100.26866.0
    state: present
    install_args: /features OptionId.DeploymentTools
```

So deleted the 'version' line and let it install the latest version.

This appears to be the problematic part of the module:
```powershell
if (Get-Module -Name DISM -ListAvailable) {
    Import-Module -Name DISM
}
else {
    # Server 2008 R2 doesn't have the DISM module installed on the path, check the Windows ADK path
    $adk_root = [System.Environment]::ExpandEnvironmentVariables("%PROGRAMFILES(X86)%\Windows Kits\*\Assessment and Deployment Kit\Deployment Tools\amd64\DISM")
    if (Test-Path -LiteralPath $adk_root) {
        Import-Module -Name (Get-Item -LiteralPath $adk_root).FullName
    }
    else {
        Fail-Json $result "The DISM PS module needs to be installed, this can be done through the windows-adk chocolately package"
    }
}`
```
The path certainly does exist.

##### EXPECTED RESULTS
Expect to apply hotfix to my Windows Server 2008r2 server.

##### ACTUAL RESULTS
"The DISM PS module needs to be installed, this can be done through the windows-adk chocolately package"
```paste below

```
