### ISSUE TITLE
win_iis_webapppool

### ISSUE THREAD

**Issue by kossioni** [ansible-collections/community.windows#566]
cannot add multiple env vars only 1 accepted using:

```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
```

From the above I see the env var added but I cannot specify a list of them no matter what I try...

for example:

TRY 1

```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
        - name: foo2
           value: bar2
```

The above doesn't work....

If I try to add multiple environmentVariables attributes only the last gets applied for example:

TRY 2

```
- name: Create IIS Application Pool
  community.windows.win_iis_webapppool:
    name: MouzakisAnsibleAppPool
    state: present
    attributes:
      managedPipelineMode: Classic
      queueLength: 2000
      processModel.identityType: SpecificUser
      processModel.userName: '{{ ansible_user }}'
      processModel.password: '{{ ansible_password }}'
      processModel.loadUserProfile: true
      processModel.maxProcesses: 20
      environmentVariables:
        - name: foo
          value: bar
      environmentVariables:
        - name: last1
          value: only_applies
```

How can I add multiple env vars?
