### ISSUE TITLE
Ability to retrieve dhcp reservation or lease without modification

### ISSUE THREAD

**Issue by dbond007** [ansible-collections/community.windows#591]
##### SUMMARY
I would like to be able to retrieve details about a reservation, specifically if its present, without modifying it.
Currently if using

```yaml
- name: Locate the dhcp assigned ip address in the dhcp server
  community.windows.win_dhcp_lease:
    mac: "{{ find_mac }}"
  register: dhcp_results
  delegate_to: "{{ dhcp_delegate }}"
```
it will fail if it isn't present, and will modify the current entry if it is. Changing the name of the reservation to reservation-{MAC}
I want to know the details only, not make any changes. This is similar to the current feature request #498 to pull all info, but i want it for the mac address for a single lease

##### ISSUE TYPE
- Allow dhcp info retrieval without modification of the current entry.

##### COMPONENT NAME
windows.win_dhcp_lease

##### ADDITIONAL INFORMATION

```yaml
- name: Locate the dhcp assigned ip address in the dhcp server
  community.windows.win_dhcp_lease:
    lookup_mac: "{{ find_mac }}"
  register: dhcp_results
  delegate_to: "{{ dhcp_delegate }}"
```
