### ISSUE TITLE
MX Record Type Support in win_dns_record

### ISSUE THREAD

**Issue by cysys-ngt** [ansible-collections/community.windows#592]
##### SUMMARY
Currently the win_dns_record module does not support MX record type.  Would like to see MX record type supported

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION
The MX record is used to identify the Exchange mail server (or any mail server) in the domain.

```yaml
win_dns_record:
    zone: "example.com"
    name: "exch"
    type: "mx"
    value: "exchange.exampe.com"
    state: present
```
