### ISSUE TITLE
Add Protocol parameter to win_dns_record

### ISSUE THREAD

**Issue by F1r3bl4d3** [ansible-collections/community.windows#594]
##### SUMMARY
Would it be possible to add a protocol parameter to win_dns_record to enable adding SRV records to "_tcp" or "_udp"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION
This would be able to automate adding a KMS 1688 SRV record into the _tcp zone

```
- name: Creating a SRV record with port number and priority
  community.windows.win_dns_record:
    name: "test"
    priority: 5
    port: 995
    state: present
    type: "SRV"
    weight: 2
    value: "amer.example.com"
    zone: "example.com"
    'protocol: "_tcp"'

```
