### ISSUE TITLE
win_scheduled_task doesn't check for invalid task names

### ISSUE THREAD

**Issue by briantist** [ansible-collections/community.windows#60]
##### SUMMARY

Scheduled task names can't contain the following characters: `\ / : * ? " < > |`
The GUI notifies you when you try as well:
![image](https://user-images.githubusercontent.com/1260690/77706904-07849e80-6f9a-11ea-9fea-7476fac66920.png)

The module doesn't validate this though. If you try to run in check mode, it won't notice the name is invalid and won't show any error.

In regular mode, I've seen the following errors so far related to trying to create a task with an invalid character (in my case the character is `:` colon):

* `failed to register new task definition: Value does not fall within the expected range.`
* `failed to register new task definition: The directory property cannot be found in the cache.`

In the first error, path was unspecified. In the second error, path was not the default root path `\`, which is probably why it differs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_scheduled_task

##### ANSIBLE VERSION

2.9.6

##### STEPS TO REPRODUCE

```yaml
---
- hosts: hostname
  gather_facts: no
  tasks:
    - win_scheduled_task:
        name: 'Task:Name'
        actions:
          - path: powershell.exe
            arguments: '-c exit'
```

##### EXPECTED RESULTS

`win_scheduled_task` should validate the name, and return a helpful error indicating the name is invalid, in check mode too.

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "msg": "failed to register new task definition: Value does not fall within the expected range."}
```
```
FAILED! => {"changed": false, "msg": "failed to register new task definition: The directory property cannot be found in the cache."}
```

In check mode: there is no error, even though there should be.
