### ISSUE TITLE
Interest in Visual Studio component and updater module?

### ISSUE THREAD

**Issue by mathstuf** [ansible-collections/community.windows#609]
##### SUMMARY
Support for Visual Studio component management and updating.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- `vs_component`: install or remove Visual Studio components
- `vs_update`: update Visual Studio installations and the installer itself

##### ADDITIONAL INFORMATION
Already coded up here: https://gitlab.kitware.com/utils/ansible.visualstudio

I was wondering if it would be accepted here rather than maintaining a completely new collection for it.

```yaml
---
- name: Install Visual Studio
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2022community
    state: latest

- name: Install VSSetup
  community.windows.win_psmodule:
    name: VSSetup
    state: latest

- name: Install Visual Studio packages
  vs_component:
    install_path: 'c:\Program Files\Microsoft Visual Studio\2022\Community'
    components:
      - Microsoft.VisualStudio.Workload.ManagedDesktop
      - Microsoft.VisualStudio.Component.Windows11SDK.22000
    include_recommended: false
    include_optional: false
    force: false
    force_download_before_install: false
    state: present

- name: Update Visual Studio packages
  vs_update:
    install_path: 'c:\Program Files\Microsoft Visual Studio\2022\Community'
    restart: false
    update_installer: 'true'  # true, only
    force_download_before_install: false
    remove_out_of_support: false
```
