### ISSUE TITLE
win_xml module: 'Unhandled exception' error at line 230. Set-StrictMode related.

### ISSUE THREAD

**Issue by robreardon** [ansible-collections/community.windows#61]
##### SUMMARY
win_xml module throws an error when trying to add a new attribute to an element. Re-opened here from original issue reported on main ansible project:
https://github.com/ansible/ansible/issues/68511

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_xml module

##### ANSIBLE VERSION

```
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

AWX Docker container 'awx_task', version 9.2.0 from Docker Hub.

I suspect that this error is due to the 'Set-StrictMode -Version 2' setting being enabled at the top of the win_xml.ps1 script.

##### STEPS TO REPRODUCE

Try to update a simple XML file element with an attribute

Example XML before change:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings></connectionStrings>
</configuration>
```

```
- name: Update XML
  hosts: all
  gather_facts: false
  serial: 1

  tasks:
    - name: Add XML attribute
      win_xml:
        path: "C:\\temp\\test.xml"
        xpath: "/configuration/connectionStrings"
        attribute: "configSource"
        fragment: "Config\\ConnectionStrings.config"
        type: attribute
```

##### EXPECTED RESULTS

Desired outcome XML:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings configSource="Config\ConnectionStrings.config"></connectionStrings>
</configuration>
```
##### ACTUAL RESULTS

A powershell error is thrown

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No File>: line 230
fatal: [host01]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: The property 'configSource' cannot be found on this object. Verify that the property exists."}
```
