### ISSUE TITLE
win_scheduled_task failed to register new task definition: (32,4):UserId:

### ISSUE THREAD

**Issue by jghal** [ansible-collections/community.windows#633]
##### SUMMARY
I'm trying to convert a `win_shell` task to `win_scheduled_task` and it's failing with `failed to register new task definition: (32,4):UserId:`. I tried updating the collection to 3.0.0 but behavior is the same. The error message appears to be from _plugins/modules/win_scheduled_task.ps1#L1107_. I can't seem to find MS docs that explain what the error means. Looking at the win_scheduled_task.ps1 and the Win32 docs for  [TaskFolder.RegisterTaskDefinition](https://learn.microsoft.com/en-us/windows/win32/taskschd/taskfolder-registertaskdefinition) I would guess that the task definition is missing the UserId. Though I'm more inclined to believe the error is in my implementation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.windows.win_scheduled_task

##### ANSIBLE VERSION

```
$ ansible --version
ansible [core 2.16.14]
  config file = /code/packer/windows2022-baseimage-pipeline/ansible.cfg
  configured module search path = ['/home/justin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/dist-packages/ansible
  ansible collection location = /home/justin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.12/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 2.3.0  
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
CONFIG_FILE() = /code/packer/windows2022-baseimage-pipeline/ansible.cfg
$ cat /code/packer/windows2022-baseimage-pipeline/ansible.cfg 
[defaults]
callback_whitelist = time, profile_tasks
```

##### OS / ENVIRONMENT

Target machine is AWS instance from Amazon's Windows_Server-2022-English-Full-Base image

##### STEPS TO REPRODUCE

```yaml
- name: Reprovisioning WinRM Certificate
  become: yes
  become_flags: logon_type=batch
  become_method: runas
  become_user: SYSTEM
  block:
    - name: Create mgmttask directory
      ansible.windows.win_file:
        path: C:\mgmttasks
        state: directory

    - name: Copy winrm_fix.ps1 in destination image
      ansible.windows.win_copy:
        src: files/winrm_fix.ps1
        dest: C:\mgmttasks\winrm_fix.ps1
      register: winrm_fix_copy

    # - name: Create Scheduled task to run-once
    #   ansible.windows.win_shell: |
    #     $destination = '-WindowStyle hidden {{ winrm_fix_copy.dest }} -ForceNewSSLCert'
    #     $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $destination
    #     $trigger = New-ScheduledTaskTrigger -AtStartup
    #     $principal = New-ScheduledTaskPrincipal -UserID "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    #     Register-ScheduledTask -TaskName 'WinRMReprovisioning' -TaskPath 'Hotfixes' -Action $action \
    #       -Trigger $trigger -Principal $principal -Description 'WinRM Reprovisioning certificate' -ErrorAction Stop
    
    - name: Create run-once scheduled WinRMReprovisioning
      community.windows.win_scheduled_task:
        name: WinRMReprovisioning
        display_name: Reconfigure WinRM on first boot
        actions:
          - arguments: -WindowStyle hidden {{ winrm_fix_copy.dest }} -ForceNewSSLCert
            path: powershell.exe
        enabled: true
        logon_type: service_account
        path: \Hotfixes
        run_level: highest
        state: present
        triggers:
          - type: boot
        username: SYSTEM
```

##### EXPECTED RESULTS

Scheduled task is created on target machine

##### ACTUAL RESULTS

```
TASK [security-agents : Create mgmttask directory] ***************************************************************
task path: /home/justin/.ansible/roles/security-agents/tasks/windows-scheduler.yml:62
ok: [ip-10-127-136-10.ec2.internal] => {"changed": false}

TASK [security-agents : Copy winrm_fix.ps1 in destination image] *************************************************
task path: /home/justin/.ansible/roles/security-agents/tasks/windows-scheduler.yml:67
ok: [ip-10-127-136-10.ec2.internal] => {"changed": false, "checksum": "cffe902cb83d8ad0ffe0c16888167e649ffd767e", "dest": "C:\\mgmttasks\\winrm_fix.ps1", "operation": "file_copy", "original_basename": "winrm_fix.ps1", "size": 15999, "src": "files/winrm_fix.ps1"}

TASK [security-agents : Create run-once scheduled WinRMReprovisioning] *******************************************
task path: /home/justin/.ansible/roles/security-agents/tasks/windows-scheduler.yml:82
fatal: [ip-10-127-136-10.ec2.internal]: FAILED! => {"changed": false, "msg": "failed to register new task definition: (32,4):UserId:"}
```
