### ISSUE TITLE
Ansible module to support the Windows package manager (winget)

### ISSUE THREAD

**Issue by JamieMagee** [ansible-collections/community.windows#89]
##### SUMMARY
I think that Ansible should support the Windows package manager, [announced at Build 2020](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_winget

##### ADDITIONAL INFORMATION
```yaml
- name: Install PowerToys
  win_winget:
    name: Microsoft.PowerToys
```
References:
- https://docs.microsoft.com/en-gb/windows/package-manager/
- https://github.com/microsoft/winget-pkgs
- https://github.com/microsoft/winget-cli
